In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

BASE_DIR = "/content/drive/MyDrive/SafeCue Audio Recordings"

print("Folder exists:", os.path.exists(BASE_DIR))
print("\nContents:")

for item in os.listdir(BASE_DIR):
    print("📁", item)

Folder exists: True

Contents:
📁 Siren
📁 Fire Alarm
📁 Smoke Alarm
📁 Screaming
📁 Background Noise

In [4]:
!pip install -q yt-dlp
!apt-get -qq update
!apt-get -qq install ffmpeg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.7/183.7 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 30.3 MB/s eta 0:00:00
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)

In [5]:
import os

METADATA_DIR = os.path.join(BASE_DIR, "_metadata")
os.makedirs(METADATA_DIR, exist_ok=True)

print("Metadata folder:", METADATA_DIR)

Metadata folder: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata

In [6]:
import pandas as pd

metadata_url = "https://research.google.com/audioset/download.html"

print("AudioSet metadata page:")
print(metadata_url)

AudioSet metadata page:
https://research.google.com/audioset/download.html

In [7]:
!wget -q --show-progress \
"https://huggingface.co/datasets/agkphysics/AudioSet/resolve/main/balanced_train_segments.csv" \
-o /dev/null

In [8]:
import os

print(os.listdir(METADATA_DIR))

[]

In [9]:
import requests

url = "https://research.google.com/audioset/download.html"
response = requests.get(url)

print("Status code:", response.status_code)
print("Page downloaded:", len(response.text) > 0)

Status code: 200
Page downloaded: True

In [10]:
import requests

url = "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/balanced_train_segments.csv"

output_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

response = requests.get(url)

with open(output_path, "wb") as f:
    f.write(response.content)

print("Downloaded:", output_path)
print("File size:", os.path.getsize(output_path), "bytes")

Downloaded: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata/balanced_train_segments.csv
File size: 1211931 bytes

In [14]:
csv_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

with open(csv_path, "r", encoding="utf-8") as f:
    for i in range(8):
        print(f"LINE {i+1}:", repr(f.readline()))

LINE 1: '# Segments csv created Sun Mar  5 10:54:31 2017\n'
LINE 2: '# num_ytids=22160, num_segs=22160, num_unique_labels=527, num_positive_labels=52882\n'
LINE 3: '# YTID, start_seconds, end_seconds, positive_labels\n'
LINE 4: '--PJHxphWEs, 30.000, 40.000, "/m/09x0r,/t/dd00088"\n'
LINE 5: '--ZhevVpy1s, 50.000, 60.000, "/m/012xff"\n'
LINE 6: '--aE2O5G5WE, 0.000, 10.000, "/m/03fwl,/m/04rlf,/m/09x0r"\n'
LINE 7: '--aO5cdqSAg, 30.000, 40.000, "/t/dd00003,/t/dd00005"\n'
LINE 8: '--aaILOrkII, 200.000, 210.000, "/m/032s66,/m/073cg4"\n'

In [15]:
import csv
import pandas as pd
import os

csv_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

rows = []

with open(csv_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if row and not row[0].startswith("#"):
            rows.append(row)

df = pd.DataFrame(
    rows,
    columns=["YTID", "start_seconds", "end_seconds", "positive_labels"]
)

print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Shape: (22160, 4)

First 5 rows:

          YTID start_seconds end_seconds             positive_labels
0  --PJHxphWEs        30.000      40.000         /m/09x0r,/t/dd00088
1  --ZhevVpy1s        50.000      60.000                   /m/012xff
2  --aE2O5G5WE         0.000      10.000  /m/03fwl,/m/04rlf,/m/09x0r
3  --aO5cdqSAg        30.000      40.000       /t/dd00003,/t/dd00005
4  --aaILOrkII       200.000     210.000         /m/032s66,/m/073cg4

In [16]:
import requests
import json
import os

ontology_url = "https://raw.githubusercontent.com/audioset/ontology/master/ontology.json"
ontology_path = os.path.join(METADATA_DIR, "ontology.json")

response = requests.get(ontology_url)
response.raise_for_status()

with open(ontology_path, "wb") as f:
    f.write(response.content)

print("Ontology downloaded successfully!")
print("File size:", os.path.getsize(ontology_path), "bytes")

Ontology downloaded successfully!
File size: 342780 bytes

In [17]:
import json

with open(ontology_path, "r", encoding="utf-8") as f:
    ontology = json.load(f)

keywords = ["siren", "fire alarm", "smoke alarm", "screaming", "background noise"]

for keyword in keywords:
    print(f"\n=== {keyword.upper()} ===")

    matches = []
    for item in ontology:
        name = item.get("name", "")
        if keyword.lower() in name.lower():
            matches.append((item.get("id"), name))

    for audio_id, name in matches:
        print(audio_id, "→", name)

=== SIREN ===
/m/04qvtq → Police car (siren)
/m/012n7d → Ambulance (siren)
/m/012ndj → Fire engine, fire truck (siren)
/m/03kmc9 → Siren
/m/0dgbq → Civil defense siren

=== FIRE ALARM ===
/m/0c3f7m → Fire alarm

=== SMOKE ALARM ===
/m/01y3hg → Smoke detector, smoke alarm

=== SCREAMING ===
/m/03qc9zr → Screaming

=== BACKGROUND NOISE ===
/m/093_4n → Background noise

In [18]:
label_ids = {
    "Siren": "/m/03kmc9",
    "Fire Alarm": "/m/0c3f7m",
    "Smoke Alarm": "/m/01y3hg",
    "Screaming": "/m/03qc9zr",
    "Background Noise": "/m/093_4n"
}

for category, label_id in label_ids.items():
    count = df["positive_labels"].apply(
        lambda x: label_id in x.split(",")
    ).sum()

    print(f"{category}: {count} clips")

Siren: 207 clips
Fire Alarm: 60 clips
Smoke Alarm: 60 clips
Screaming: 59 clips
Background Noise: 0 clips

In [19]:
import requests
import os

url = "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/unbalanced_train_segments.csv"

output_path = os.path.join(METADATA_DIR, "unbalanced_train_segments.csv")

response = requests.get(url)
response.raise_for_status()

with open(output_path, "wb") as f:
    f.write(response.content)

print("Downloaded successfully!")
print("File size:", os.path.getsize(output_path), "bytes")

Downloaded successfully!
File size: 101468408 bytes

In [20]:
import csv
from collections import Counter

unbalanced_path = os.path.join(
    METADATA_DIR,
    "unbalanced_train_segments.csv"
)

counts = Counter()

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        for category, label_id in label_ids.items():
            if label_id in labels:
                counts[category] += 1

print("AudioSet unbalanced training counts:")
for category in label_ids:
    print(f"{category}: {counts[category]} clips")

AudioSet unbalanced training counts:
Siren: 8079 clips
Fire Alarm: 801 clips
Smoke Alarm: 426 clips
Screaming: 1126 clips
Background Noise: 0 clips

In [21]:
siren_id = "/m/03kmc9"

siren_rows = df[
    df["positive_labels"].apply(
        lambda x: siren_id in x.split(",")
    )
].reset_index(drop=True)

print("Siren clips available:", len(siren_rows))
print("\nFirst Siren clip:")
display(siren_rows.head(1))

Siren clips available: 207

First Siren clip:

,YTID,start_seconds,end_seconds,positive_labels
0,-4RWqM0UCCY,0.000,10.000,"/m/012n7d,/m/02mfyn,/m/03j1ly,/m/03kmc9"

In [23]:
import subprocess
import os
import time

# Number of clips to test
NUM_TEST = 10

# Use the first 10 Siren clips
test_rows = siren_rows.head(NUM_TEST)

siren_folder = os.path.join(BASE_DIR, "Siren")
os.makedirs(siren_folder, exist_ok=True)

success = 0
failed = 0

for i, row in test_rows.iterrows():
    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        siren_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # Skip if already downloaded
    if os.path.exists(output_file):
        print(f"Already exists: {ytid}")
        success += 1
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(f"Downloading {success + failed + 1}/{NUM_TEST}: {ytid}")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        success += 1
        print("  ✅ Success")
    else:
        failed += 1
        print("  ❌ Failed")

    time.sleep(1)

print("\n====================")
print("DOWNLOAD TEST COMPLETE")
print("====================")
print("Successful:", success)
print("Failed:", failed)

Already exists: -4RWqM0UCCY
Downloading 2/10: -Y1qiiugnk8
  ✅ Success
Downloading 3/10: -_dElQcyJnA
  ✅ Success
Downloading 4/10: -gKNRXbpAKs
  ✅ Success
Downloading 5/10: -oSw8wNpLcY
  ✅ Success
Downloading 6/10: -z47zN0YyE4
  ✅ Success
Downloading 7/10: 03NLMEMi8-I
  ✅ Success
Downloading 8/10: 0JKcTVpby0I
  ✅ Success
Downloading 9/10: 0JPT13OUVV8
  ✅ Success
Downloading 10/10: 0PhU-PIsUMw
  ✅ Success

====================
DOWNLOAD TEST COMPLETE
====================
Successful: 10
Failed: 0

In [24]:
# Create a list of unique Siren YouTube sources
# We will use this list for the larger download.

siren_candidates = siren_rows.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print("Total Siren candidates:", len(siren_candidates))
print("\nFirst 10 candidates:")
display(siren_candidates.head(10))

Total Siren candidates: 207

First 10 candidates:

,YTID,start_seconds,end_seconds,positive_labels
0,-4RWqM0UCCY,0.000,10.000,"/m/012n7d,/m/02mfyn,/m/03j1ly,/m/03kmc9"
1,-Y1qiiugnk8,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9"
2,-_dElQcyJnA,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9,/m/04qvtq"
3,-gKNRXbpAKs,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9,/m/0dgbq"
4,-oSw8wNpLcY,60.000,70.000,"/m/030rvx,/m/03kmc9"
5,-z47zN0YyE4,420.000,430.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
6,03NLMEMi8-I,30.000,40.000,"/m/03kmc9,/m/0dgbq"
7,0JKcTVpby0I,30.000,40.000,"/m/03kmc9,/m/0dgbq"
8,0JPT13OUVV8,220.000,230.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
9,0PhU-PIsUMw,80.000,90.000,"/m/03kmc9,/m/0dgbq"

In [25]:
import csv
import pandas as pd
import os

unbalanced_path = os.path.join(
    METADATA_DIR,
    "unbalanced_train_segments.csv"
)

siren_id = "/m/03kmc9"

siren_unbalanced_rows = []

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        if siren_id in labels:
            siren_unbalanced_rows.append(row)

siren_unbalanced = pd.DataFrame(
    siren_unbalanced_rows,
    columns=["YTID", "start_seconds", "end_seconds", "positive_labels"]
)

# Remove duplicate YouTube videos
siren_unbalanced = siren_unbalanced.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print("Unique Siren candidates in unbalanced set:", len(siren_unbalanced))
display(siren_unbalanced.head(10))

Unique Siren candidates in unbalanced set: 8079

,YTID,start_seconds,end_seconds,positive_labels
0,--7T50tAIrg,6.000,16.000,"/m/03kmc9,/m/09x0r"
1,-09rxiqNNEs,30.000,40.000,"/m/03kmc9,/m/0dgbq"
2,-0Eem_FuIto,15.000,25.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
3,-122tCXtFhU,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq,/m/07yv9,/m/0k4j"
4,-2GlU3e0nTU,170.000,180.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"
5,-34Lznw_wUA,10.000,20.000,/m/03kmc9
6,-3qh-WFUV2U,30.000,40.000,"/m/03kmc9,/m/0dgbq"
7,-4JG_Ag99hY,30.000,40.000,"/m/03kmc9,/m/0dgbq"
8,-5EiLqHCLuI,0.000,10.000,"/m/012n7d,/m/03j1ly,/m/03kmc9"
9,-5o4C4ZtHSU,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"

In [26]:
# Select 260 Siren candidates for downloading
# We use a fixed random seed so the selection is reproducible.

SIREN_TARGET = 260

siren_download_candidates = siren_unbalanced.sample(
    n=SIREN_TARGET,
    random_state=42
).reset_index(drop=True)

print("Siren candidates selected:", len(siren_download_candidates))

display(siren_download_candidates.head(10))

Siren candidates selected: 260

,YTID,start_seconds,end_seconds,positive_labels
0,JngI6xTRE2o,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9,/m/04qvtq"
1,uaFJj5A9jCE,2.000,12.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
2,w8IVfFqEXjw,60.000,70.000,"/m/03kmc9,/m/0dgbq"
3,ysJhEu_L7lc,30.000,40.000,/m/03kmc9
4,r-ww2qIp1BE,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"
5,NHcHQ6ptBmA,30.000,40.000,/m/03kmc9
6,ctyG4PM_rtw,0.000,10.000,"/m/0342h,/m/03kmc9,/m/04szw,/m/0fx80y"
7,azXoLk-FCrU,30.000,40.000,"/m/03kmc9,/m/04qvtq,/m/07yv9"
8,CiYGv42LsZ8,28.000,38.000,"/m/03kmc9,/m/07yv9,/m/0k4j"
9,axOkcNpjyb4,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"

In [27]:
import subprocess
import os
import time
import pandas as pd

siren_folder = os.path.join(BASE_DIR, "Siren")
os.makedirs(siren_folder, exist_ok=True)

results = []

for i, row in siren_download_candidates.iterrows():

    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        siren_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # If already downloaded, don't download again
    if os.path.exists(output_file):
        print(f"{i+1}/{len(siren_download_candidates)} ✅ Already exists: {ytid}")

        results.append({
            "YTID": ytid,
            "start_seconds": start,
            "end_seconds": end,
            "label": "Siren",
            "filename": output_file,
            "status": "already_exists"
        })
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(f"{i+1}/{len(siren_download_candidates)} Downloading: {ytid}")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        status = "success"
        print("   ✅ Success")
    else:
        status = "failed"
        print("   ❌ Failed")

    results.append({
        "YTID": ytid,
        "start_seconds": start,
        "end_seconds": end,
        "label": "Siren",
        "filename": output_file if status == "success" else "",
        "status": status
    })

    time.sleep(1)

# Save download results
download_results = pd.DataFrame(results)

results_path = os.path.join(
    METADATA_DIR,
    "siren_download_results.csv"
)

download_results.to_csv(results_path, index=False)

print("\n==============================")
print("SIREN DOWNLOAD COMPLETE")
print("==============================")
print("Successful:", (download_results["status"] == "success").sum())
print("Already existed:", (download_results["status"] == "already_exists").sum())
print("Failed:", (download_results["status"] == "failed").sum())
print("Results saved to:", results_path)

1/260 Downloading: JngI6xTRE2o
   ✅ Success
2/260 Downloading: uaFJj5A9jCE
   ✅ Success
3/260 Downloading: w8IVfFqEXjw
   ✅ Success
4/260 Downloading: ysJhEu_L7lc
   ✅ Success
5/260 Downloading: r-ww2qIp1BE
   ❌ Failed
6/260 Downloading: NHcHQ6ptBmA
   ✅ Success
7/260 Downloading: ctyG4PM_rtw
   ✅ Success
8/260 Downloading: azXoLk-FCrU
   ✅ Success
9/260 Downloading: CiYGv42LsZ8
   ✅ Success
10/260 Downloading: axOkcNpjyb4
   ✅ Success
11/260 Downloading: 1Q61oRUkfC0
   ✅ Success
12/260 Downloading: Lg6yI5szlVw
   ✅ Success
13/260 Downloading: yDeuZ92Y0eQ
   ✅ Success
14/260 Downloading: 2iKT4cvbJy8
   ❌ Failed
15/260 Downloading: 3LblLgNthRs
   ✅ Success
16/260 Downloading: FF410bQhJ8s
   ✅ Success
17/260 Downloading: HWeSf6Dsa5g
   ✅ Success
18/260 Downloading: 79-rErKgp3s
   ✅ Success
19/260 Downloading: vVEpMHmcH5Q
   ✅ Success
20/260 Downloading: eRZyNpT-XB8
   ✅ Success
21/260 Downloading: lAyZQxneqGA
   ✅ Success
22/260 Downloading: 0rdPzsSkzOU
   ✅ Success
23/260 Downloading: 0vKWXrc8PZo
   ❌ Failed
24/260 Downloading: E__SrkG0dvQ
   ✅ Success
25/260 Downloading: y8LYuwp5g-Y
   ✅ Success
26/260 Downloading: eY7_EkQ84UI
   ✅ Success
27/260 Downloading: WtzkncVLdKA
   ✅ Success
28/260 Downloading: 5OrXB62YfqY
   ✅ Success
29/260 Downloading: _mtDau5zA5k
   ❌ Failed
30/260 Downloading: JxIFYhhW1yw
   ✅ Success
31/260 Downloading: VC0vIx1a6Xg
   ✅ Success
32/260 Downloading: f_tW6gPPxrc
   ✅ Success
33/260 Downloading: 1d7RTWiSszo
   ✅ Success
34/260 Downloading: T9YB50TPbNQ
   ✅ Success
35/260 Downloading: lGqGGqSt784
   ✅ Success
36/260 Downloading: KBBzBNojAzM
   ✅ Success
37/260 Downloading: m4FXx4DA6CM
   ✅ Success
38/260 Downloading: lrMU3eGqw8A
   ✅ Success
39/260 Downloading: FrUZ9YYDzNY
   ✅ Success
40/260 Downloading: 9dLUJRQELfk
   ✅ Success
41/260 Downloading: hoIiES5qHHU
   ✅ Success
42/260 Downloading: djG_6S2I_EQ
   ✅ Success
43/260 Downloading: eD7bF8jdDzk
   ✅ Success
44/260 Downloading: IPRSfGhKCk4
   ✅ Success
45/260 Downloading: 1SGSVCCovqs
   ❌ Failed
46/260 Downloading: P0rf0FeDuSo
   ✅ Success
47/260 Downloading: KvoVUZQ9520
   ✅ Success
48/260 Downloading: IyUIHp3z7o4
   ✅ Success
49/260 Downloading: RbCskQNDntc
   ✅ Success
50/260 Downloading: N4d41fjHTd8
   ✅ Success
51/260 Downloading: uIwIEhjXhp0
   ❌ Failed
52/260 Downloading: wiWtK8SnXeE
   ✅ Success
53/260 Downloading: m-krD26VgMc
   ✅ Success
54/260 Downloading: VpVQSzhSd14
   ✅ Success
55/260 Downloading: VeCP6mZbbCQ
   ✅ Success
56/260 Downloading: qSwc-5_tdZ8
   ✅ Success
57/260 Downloading: QVRwOOczbkQ
   ❌ Failed
58/260 Downloading: CjBEYyY_zAo
   ❌ Failed
59/260 Downloading: eX5Arj3tCtk
   ✅ Success
60/260 Downloading: b1IDJ3pESyQ
   ✅ Success
61/260 Downloading: 5nwMi6jIBsw
   ❌ Failed
62/260 Downloading: nT1D2vwXmpc
   ✅ Success
63/260 Downloading: 8HASYg_rWtI
   ✅ Success
64/260 Downloading: Ll_q4ROVnpM
   ✅ Success
65/260 Downloading: k2QmGOZTgI4
   ✅ Success
66/260 Downloading: IbNRbt85y2U
   ✅ Success
67/260 Downloading: ShT9kuMlRWg
   ✅ Success
68/260 Downloading: qujAC8ix2iU
   ✅ Success
69/260 Downloading: 9CKXMBiPZM4
   ✅ Success
70/260 Downloading: 0og-bzSSVn8
   ❌ Failed
71/260 Downloading: BzLItAMFXto
   ✅ Success
72/260 Downloading: 52Yoee8fbLI
   ✅ Success
73/260 Downloading: qUuUpSIeo4g
   ✅ Success
74/260 Downloading: 4_ZZFKjjoL0
   ✅ Success
75/260 Downloading: rkw6PdThaxQ
   ✅ Success
76/260 Downloading: o9xCASah21I
   ✅ Success
77/260 Downloading: gpecurYnY2k
   ✅ Success
78/260 Downloading: cX9NRa9P2oU
   ✅ Success
79/260 Downloading: sXVRrpisEbg
   ✅ Success
80/260 Downloading: soDWe_mNYYg
   ✅ Success
81/260 Downloading: An4ZXnZAaoo
   ❌ Failed
82/260 Downloading: 9YKzan280sE
   ✅ Success
83/260 Downloading: eSyA_RsT1nc
   ✅ Success
84/260 Downloading: Tb6yv56nGao
   ❌ Failed
85/260 Downloading: x-rrn1-wZH4
   ✅ Success
86/260 Downloading: 9VAIrq9d-Iw
   ✅ Success
87/260 Downloading: fL-vp4_Ap-k
   ✅ Success
88/260 Downloading: qgLDdlvdBGQ
   ✅ Success
89/260 Downloading: UX8eJYcKS3k
   ✅ Success
90/260 Downloading: L52CaHaHrZc
   ✅ Success
91/260 Downloading: msdg7CXgrHU
   ✅ Success
92/260 Downloading: H_VpJUoVtI4
   ✅ Success
93/260 Downloading: Jv8yXmBjEnc
   ✅ Success
94/260 Downloading: G_l1XUlFF4E
   ✅ Success
95/260 Downloading: Ak0wxUETZS8
   ✅ Success
96/260 Downloading: zU1D3Ze3PZ0
   ✅ Success
97/260 Downloading: TMj00-mVkYc
   ✅ Success
98/260 Downloading: LjHOYz7q1YQ
   ✅ Success
99/260 Downloading: WhJ3Urk2uUA
   ✅ Success
100/260 Downloading: Sm_670Aqo5g
   ✅ Success
101/260 Downloading: a8-_OiB1sJY
   ✅ Success
102/260 Downloading: C2TYCbmHxck
   ✅ Success
103/260 Downloading: 82JA1D4xleE
   ✅ Success
104/260 Downloading: 3M3FsgEyWW8
   ✅ Success
105/260 Downloading: Y6KnuVj8OZQ
   ✅ Success
106/260 Downloading: 6rSD9uaIAQw
   ✅ Success
107/260 Downloading: 8tWvr59ebM8
   ✅ Success
108/260 Downloading: NXD8HAe31bM
   ✅ Success
109/260 Downloading: HXaBF2nmsms
   ✅ Success
110/260 Downloading: 3SilJJGInak
   ❌ Failed
111/260 Downloading: _JjkMCq9pNQ
   ✅ Success
112/260 Downloading: yAXvUPPYnpk
   ✅ Success
113/260 Downloading: -r7Yk-N2Z4U
   ✅ Success
114/260 Downloading: j3_k93jEWtU
   ✅ Success
115/260 Downloading: T56RZeirWQo
   ✅ Success
116/260 Downloading: tkiXsMogwZE
   ✅ Success
117/260 Downloading: cBYAkkaX8G4
   ✅ Success
118/260 Downloading: NdLuP-KlScQ
   ✅ Success
119/260 Downloading: gtx3zFfXh-s
   ❌ Failed
120/260 Downloading: h6b8EQ9Rso0
   ❌ Failed
121/260 Downloading: m1lAISBFvxE
   ✅ Success
122/260 Downloading: 9JLNq3hDOY0
   ✅ Success
123/260 Downloading: 1RcjvfLX8Ms
   ❌ Failed
124/260 Downloading: AoAfewp_kaY
   ✅ Success
125/260 Downloading: 2WMjVrY444M
   ✅ Success
126/260 Downloading: t5RfGyNwR5w
   ❌ Failed
127/260 Downloading: zC3dmdnv1KY
   ✅ Success
128/260 Downloading: 3CuNbYB5scs
   ✅ Success
129/260 Downloading: EGVceuMZU3o
   ✅ Success
130/260 Downloading: gqRqHm6gAS0
   ✅ Success
131/260 Downloading: ngHmt25_--M
   ✅ Success
132/260 Downloading: iQ5lVnRRooE
   ✅ Success
133/260 Downloading: 89Ln2tDYVyU
   ✅ Success
134/260 Downloading: f_7eK3sqN7M
   ✅ Success
135/260 Downloading: i4odiaaqrfQ
   ✅ Success
136/260 Downloading: sbgGB3DRo5g
   ✅ Success
137/260 Downloading: UWxYo-rB1vI
   ✅ Success
138/260 Downloading: IPKni-3INXQ
   ✅ Success
139/260 Downloading: cP0KDo0H944
   ✅ Success
140/260 Downloading: KNcYRuDt02M
   ✅ Success
141/260 Downloading: 9m6i3tZaqS0
   ✅ Success
142/260 Downloading: TJ_7iTquH-I
   ✅ Success
143/260 Downloading: 6ouVOgddKoc
   ✅ Success
144/260 Downloading: D8nus_iz9sA
   ✅ Success
145/260 Downloading: qM4htNJL-iw
   ✅ Success
146/260 Downloading: dPcmsMfoeTU
   ✅ Success
147/260 Downloading: gy6PrIiLh6I
   ✅ Success
148/260 Downloading: 4Vltzmw0O3Y
   ✅ Success
149/260 Downloading: pcmatMy0-XY
   ✅ Success
150/260 Downloading: imO76QQACec
   ✅ Success
151/260 Downloading: YB7_horpUGQ
   ✅ Success
152/260 Downloading: kCyej2X1Sf8
   ✅ Success
153/260 Downloading: iYxMhVSOC9Y
   ✅ Success
154/260 Downloading: 4vCBb5s41Ms
   ✅ Success
155/260 Downloading: FL7EAu5HZM8
   ✅ Success
156/260 Downloading: megW4yRhdYA
   ❌ Failed
157/260 Downloading: yxZ28BjFeM0
   ✅ Success
158/260 Downloading: 7JseGlbiLx8
   ❌ Failed
159/260 Downloading: ryBtQ672mDY
   ✅ Success
160/260 Downloading: Rfy8aecdhO8
   ✅ Success
161/260 Downloading: 7VrxYYOWQ6o
   ❌ Failed
162/260 Downloading: CupakwHJSFw
   ✅ Success
163/260 Downloading: nAxyUNUuI_Y
   ✅ Success
164/260 Downloading: RkL41-4yG1Q
   ✅ Success
165/260 Downloading: AfsghWF11bg
   ❌ Failed
166/260 Downloading: TGwxnxvq8d0
   ✅ Success
167/260 Downloading: WDk_ccFHrZw
   ✅ Success
168/260 Downloading: yLd5HqLiFQw
   ✅ Success
169/260 Downloading: SeJ-8_KxfRg
   ❌ Failed
170/260 Downloading: 13J_WcKx3Qo
   ✅ Success
171/260 Downloading: HMlVK92Vrgw
   ✅ Success
172/260 Downloading: rZUq56OMlPA
   ❌ Failed
173/260 Downloading: 9gCfNKhR3-g
   ✅ Success
174/260 Downloading: B066YDLDvh0
   ✅ Success
175/260 Downloading: xDqpS908aCA
   ✅ Success
176/260 Downloading: srNmFdjxikw
   ✅ Success
177/260 Downloading: SK-rH-2i7-Q
   ✅ Success
178/260 Downloading: TpIy4vjeQZ0
   ✅ Success
179/260 Downloading: J4GgFgjpbuQ
   ✅ Success
180/260 Downloading: jpPEG7GadK8
   ✅ Success
181/260 Downloading: zbg5qfJv3_E
   ❌ Failed
182/260 Downloading: 6rXgD5JlYxY
   ✅ Success
183/260 Downloading: 6yUlo4JLfjM
   ✅ Success
184/260 Downloading: s9kARv7Q3Iw
   ✅ Success
185/260 Downloading: IPFeBuT9EPU
   ❌ Failed
186/260 Downloading: 8BMP10rXheA
   ✅ Success
187/260 Downloading: hL2ojQqB5s0
   ✅ Success
188/260 Downloading: HN44iil7vig
   ❌ Failed
189/260 Downloading: LQdBczSrxh4
   ✅ Success
190/260 Downloading: EgMHjS0bETc
   ✅ Success
191/260 Downloading: 7MOvW1MpbTs
   ❌ Failed
192/260 Downloading: bc7-Uv_5BEA
   ✅ Success
193/260 Downloading: OznJrXrSegE
   ✅ Success
194/260 Downloading: EZ6WrRosvlo
   ❌ Failed
195/260 Downloading: yTk51Fd59Zo
   ✅ Success
196/260 Downloading: Bvrj8fbttTo
   ✅ Success
197/260 Downloading: kUXyYT0l9QY
   ✅ Success
198/260 Downloading: DZ1ZtVAXbTg
   ✅ Success
199/260 Downloading: VgnX5QCMBTQ
   ❌ Failed
200/260 Downloading: 82eOAbQe3tk
   ✅ Success
201/260 Downloading: xKz9z_eEq3s
   ❌ Failed
202/260 Downloading: sT6ZISqsSfA
   ❌ Failed
203/260 Downloading: LjgjqdENqHs
   ❌ Failed
204/260 Downloading: boFaPXi80RI
   ✅ Success
205/260 Downloading: HhAYsIJB7Ug
   ✅ Success
206/260 Downloading: BVhISZcrrI0
   ❌ Failed
207/260 Downloading: QpqHkEBZ0Ao
   ✅ Success
208/260 Downloading: 4mQIYQmVYWQ
   ✅ Success
209/260 Downloading: mNtqZo6DNKI
   ✅ Success
210/260 Downloading: W9gJ7g0bbvs
   ✅ Success
211/260 Downloading: XQxdQBggiPA
   ✅ Success
212/260 Downloading: QVyYjJLKNl8
   ✅ Success
213/260 Downloading: Uxe-6s7__wA
   ✅ Success
214/260 Downloading: GACIkkMwTWw
   ✅ Success
215/260 Downloading: OhpPejVhlAI
   ✅ Success
216/260 Downloading: GDGq_8bFVxQ
   ✅ Success
217/260 Downloading: dF3R9d-NA_A
   ✅ Success
218/260 Downloading: BZmsjEHQf4k
   ✅ Success
219/260 Downloading: yyy2GCpeGgA
   ✅ Success
220/260 Downloading: fdIj-BzqnmU
   ✅ Success
221/260 Downloading: qg4n3pA9VXc
   ✅ Success
222/260 Downloading: Y-5_affLgXU
   ✅ Success
223/260 Downloading: NVuxT7-9fb8
   ✅ Success
224/260 Downloading: 7CE4DVXEnXQ
   ❌ Failed
225/260 Downloading: aqA9tTQNKuQ
   ✅ Success
226/260 Downloading: Jrm2HZB12_4
   ✅ Success
227/260 Downloading: wJH-9PLOcA0
   ❌ Failed
228/260 Downloading: yx-6tARu5mc
   ✅ Success
229/260 Downloading: egQQnBz5kyo
   ❌ Failed
230/260 Downloading: -B68bRDzQi8
   ✅ Success
231/260 Downloading: IRguTZG7Z6Y
   ✅ Success
232/260 Downloading: zcKrANpkVFU
   ✅ Success
233/260 Downloading: Z55hpcXVE4M
   ✅ Success
234/260 Downloading: EzVLl-tadGA
   ✅ Success
235/260 Downloading: KrUIbD-LqIY
   ✅ Success
236/260 Downloading: faidugZ8Lh0
   ✅ Success
237/260 Downloading: SsG2EriUrDo
   ✅ Success
238/260 Downloading: sS4NEhWjRss
   ✅ Success
239/260 Downloading: ERvQPTTWugE
   ✅ Success
240/260 Downloading: 5keujP8jp98
   ✅ Success
241/260 Downloading: FaxWqQazOlk
   ✅ Success
242/260 Downloading: p6dxe62YYbQ
   ❌ Failed
243/260 Downloading: iD9RhUTIqVE
   ✅ Success
244/260 Downloading: dIwvrN5x_mU
   ✅ Success
245/260 Downloading: a9KJpVbt1T0
   ✅ Success
246/260 Downloading: V90vfoGo6hg
   ✅ Success
247/260 Downloading: -_u5wrx8Ffo
   ✅ Success
248/260 Downloading: NWrGrp7ynj0
   ✅ Success
249/260 Downloading: VeCSHwtkBZU
   ✅ Success
250/260 Downloading: 2xWH7McfIVA
   ✅ Success
251/260 Downloading: 2guF3-4V-NY
   ❌ Failed
252/260 Downloading: t39KsRsRHYk
   ✅ Success
253/260 Downloading: ac_NV-KVbyo
   ✅ Success
254/260 Downloading: nayZ_NorgcM
   ✅ Success
255/260 Downloading: pIpTRHXyLb4
   ✅ Success
256/260 Downloading: lJLxyqixPQI
   ✅ Success
257/260 Downloading: _f6h4szQ994
   ✅ Success
258/260 Downloading: FhVgZ4jc0sc
   ✅ Success
259/260 Downloading: DqAedcp5q6s
   ✅ Success
260/260 Downloading: W5iexBflhRs
   ✅ Success

==============================
SIREN DOWNLOAD COMPLETE
==============================
Successful: 222
Already existed: 0
Failed: 38
Results saved to: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata/siren_download_results.csv

In [28]:
# Get Fire Alarm candidates from AudioSet unbalanced metadata

fire_alarm_id = label_ids["Fire Alarm"]

fire_alarm_rows = []

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        if fire_alarm_id in labels:
            fire_alarm_rows.append(row)

fire_alarm_candidates = pd.DataFrame(
    fire_alarm_rows,
    columns=["YTID", "start_seconds", "end_seconds", "positive_labels"]
)

fire_alarm_candidates = fire_alarm_candidates.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print("Unique Fire Alarm candidates:", len(fire_alarm_candidates))
display(fire_alarm_candidates.head(10))

Unique Fire Alarm candidates: 801

          YTID start_seconds end_seconds              positive_labels
0  --OMDPXfO6o         9.000      19.000  /m/04rlf,/m/09x0r,/m/0c3f7m
1  -6KfoGO_o9M       220.000     230.000           /m/09x0r,/m/0c3f7m
2  -E9o4ywIoj8        10.000      20.000                    /m/0c3f7m
3  -GSPHFcDEA0       190.000     200.000           /m/09x0r,/m/0c3f7m
4  -M88hG5X8fQ        10.000      20.000                    /m/0c3f7m
5  -US7xnb1Lrw         0.000      10.000           /m/09x0r,/m/0c3f7m
6  -a9xYse4q-Y        70.000      80.000          /m/030rvx,/m/0c3f7m
7  -mDOld5RYxw        80.000      90.000           /m/09x0r,/m/0c3f7m
8  -ofHiiMgeuA         0.000       8.000          /m/030rvx,/m/0c3f7m
9  -syuIC_bDQQ        10.000      20.000                    /m/0c3f7m

In [29]:
# Select Fire Alarm download candidates

FIRE_ALARM_TARGET = 260

fire_alarm_download_candidates = fire_alarm_candidates.sample(
    n=FIRE_ALARM_TARGET,
    random_state=42
).reset_index(drop=True)

print("Fire Alarm candidates selected:", len(fire_alarm_download_candidates))
display(fire_alarm_download_candidates.head(10))

Fire Alarm candidates selected: 260

,YTID,start_seconds,end_seconds,positive_labels
0,r0bhxdy3Ovk,30.000,40.000,"/m/09x0r,/m/0c3f7m"
1,njaBuEnV_LA,490.000,500.000,"/m/09x0r,/m/0c3f7m"
2,3ZrCn3Pujmo,0.000,10.000,/m/0c3f7m
3,cXqSnVsyR9g,30.000,40.000,"/m/01y3hg,/m/0c3f7m"
4,3kK9NzuMc5I,30.000,40.000,"/m/01y3hg,/m/0c3f7m"
5,kOfRBAucXV8,240.000,250.000,"/m/01y3hg,/m/030rvx,/m/09x0r,/m/0c3f7m"
6,Ni79i-5PfA4,500.000,510.000,"/m/01y3hg,/m/09x0r,/m/0c3f7m"
7,YzylenmRMT4,100.000,110.000,"/m/09x0r,/m/0c3f7m"
8,eUw5JADu-0I,420.000,430.000,/m/0c3f7m
9,W_HhkSI07ms,340.000,350.000,"/m/01y3hg,/m/09x0r,/m/0c3f7m,/t/dd00125"

In [30]:
# Download Fire Alarm clips from YouTube

import subprocess
import os
import time
import pandas as pd

fire_alarm_folder = os.path.join(BASE_DIR, "Fire Alarm")
os.makedirs(fire_alarm_folder, exist_ok=True)

results = []

for i, row in fire_alarm_download_candidates.iterrows():

    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        fire_alarm_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # If already downloaded, don't download again
    if os.path.exists(output_file):
        print(f"{i+1}/{len(fire_alarm_download_candidates)} ✅ Already exists: {ytid}")

        results.append({
            "YTID": ytid,
            "start_seconds": start,
            "end_seconds": end,
            "label": "Fire Alarm",
            "filename": output_file,
            "status": "already_exists"
        })
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(f"{i+1}/{len(fire_alarm_download_candidates)} Downloading: {ytid}")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        status = "success"
        print("   ✅ Success")
    else:
        status = "failed"
        print("   ❌ Failed")

    results.append({
        "YTID": ytid,
        "start_seconds": start,
        "end_seconds": end,
        "label": "Fire Alarm",
        "filename": output_file if status == "success" else "",
        "status": status
    })

    time.sleep(1)

# Save download results
fire_alarm_download_results = pd.DataFrame(results)

results_path = os.path.join(
    METADATA_DIR,
    "fire_alarm_download_results.csv"
)

fire_alarm_download_results.to_csv(results_path, index=False)

print("\n==============================")
print("FIRE ALARM DOWNLOAD COMPLETE")
print("==============================")
print("Successful:", (fire_alarm_download_results["status"] == "success").sum())
print("Already existed:", (fire_alarm_download_results["status"] == "already_exists").sum())
print("Failed:", (fire_alarm_download_results["status"] == "failed").sum())
print("Results saved to:", results_path)

1/260 Downloading: r0bhxdy3Ovk
   ❌ Failed
2/260 Downloading: njaBuEnV_LA
   ✅ Success
3/260 Downloading: 3ZrCn3Pujmo
   ✅ Success
4/260 Downloading: cXqSnVsyR9g
   ✅ Success
5/260 Downloading: 3kK9NzuMc5I
   ✅ Success
6/260 Downloading: kOfRBAucXV8
   ✅ Success
7/260 Downloading: Ni79i-5PfA4
   ✅ Success
8/260 Downloading: YzylenmRMT4
   ❌ Failed
9/260 Downloading: eUw5JADu-0I
   ❌ Failed
10/260 Downloading: W_HhkSI07ms
   ✅ Success
11/260 Downloading: 3fJxf2rM990
   ❌ Failed
12/260 Downloading: JU7PS1d2Kic
   ✅ Success
13/260 Downloading: lTK9IgErMA8
   ✅ Success
14/260 Downloading: 3kKfwoe57Eg
   ✅ Success
15/260 Downloading: MaMfDJzAsfc
   ✅ Success
16/260 Downloading: RSo_EFbrVtw
   ✅ Success
17/260 Downloading: Gq0CHblLoqQ
   ❌ Failed
18/260 Downloading: Q2G7rwCx5sc
   ✅ Success
19/260 Downloading: jB1xSB8MojQ
   ✅ Success
20/260 Downloading: c7rAitgz6js
   ✅ Success
21/260 Downloading: n58oIcI9WUU
   ✅ Success
22/260 Downloading: cGWHsTypfP0
   ✅ Success
23/260 Downloading: kTqM4QRmuAY
   ✅ Success
24/260 Downloading: t5C65rriar0
   ❌ Failed
25/260 Downloading: OlGqWXxOVcY
   ✅ Success
26/260 Downloading: 1xkIrZWnqMI
   ✅ Success
27/260 Downloading: HT7fW_DfUfI
   ❌ Failed
28/260 Downloading: l_vWAJf-mvw
   ✅ Success
29/260 Downloading: icPBKqFUo_A
   ✅ Success
30/260 Downloading: fxfQFaScq0E
   ✅ Success
31/260 Downloading: ErmSOdi-Iqw
   ❌ Failed
32/260 Downloading: 4dXcz9B3sV8
   ✅ Success
33/260 Downloading: gjbncB9kLeM
   ❌ Failed
34/260 Downloading: QVJ0NATvxHI
   ❌ Failed
35/260 Downloading: 2LorpXnJpYw
   ✅ Success
36/260 Downloading: 1-oAfTZfP2k
   ❌ Failed
37/260 Downloading: og6fB7FowDE
   ✅ Success
38/260 Downloading: Ri0vScq2odc
   ✅ Success
39/260 Downloading: ziAGylX7qFo
   ✅ Success
40/260 Downloading: ioWizng27ok
   ✅ Success
41/260 Downloading: 8n2I9d3NZH8
   ❌ Failed
42/260 Downloading: H1gsd1JV730
   ✅ Success
43/260 Downloading: BcUrwkum-nQ
   ✅ Success
44/260 Downloading: MF2hxT9su7A
   ✅ Success
45/260 Downloading: iNn65i8jk7U
   ✅ Success
46/260 Downloading: c7ehwoj5vUE
   ❌ Failed
47/260 Downloading: UH32kJ33izk
   ✅ Success
48/260 Downloading: iW_40jBKQX0
   ✅ Success
49/260 Downloading: vkXj2UGc2FY
   ❌ Failed
50/260 Downloading: cXxM_85cTQ8
   ✅ Success
51/260 Downloading: HtfXWNhIAIc
   ✅ Success
52/260 Downloading: 6s5ZfIFZ7lY
   ✅ Success
53/260 Downloading: ngR_af6AfHc
   ✅ Success
54/260 Downloading: JpxcqnzJxlE
   ✅ Success
55/260 Downloading: N83KBYttKuE
   ✅ Success
56/260 Downloading: P7rl7vZq794
   ✅ Success
57/260 Downloading: W0uh_rBExlo
   ✅ Success
58/260 Downloading: N1kgY9YAMQA
   ✅ Success
59/260 Downloading: Dd5F9fn46gI
   ✅ Success
60/260 Downloading: BKLbXlQpXCM
   ✅ Success
61/260 Downloading: YEKUbajRSLA
   ✅ Success
62/260 Downloading: t7xwCFnzAZM
   ✅ Success
63/260 Downloading: mjK3cLMkgZw
   ✅ Success
64/260 Downloading: L9cS68U1T7g
   ✅ Success
65/260 Downloading: FtHuuUsUrMo
   ❌ Failed
66/260 Downloading: UC7I-baXTIo
   ✅ Success
67/260 Downloading: 2mE6BPJhW3A
   ✅ Success
68/260 Downloading: yj9qTG8FN_w
   ✅ Success
69/260 Downloading: OgNck7iHeg8
   ✅ Success
70/260 Downloading: 5GFWog3rkOo
   ✅ Success
71/260 Downloading: oy-ZMaQbe9c
   ✅ Success
72/260 Downloading: CnrFcasxKkY
   ✅ Success
73/260 Downloading: zgqrUoLS-Ck
   ✅ Success
74/260 Downloading: 23xdTaTmoeI
   ✅ Success
75/260 Downloading: 1ylXVGkylyU
   ❌ Failed
76/260 Downloading: Djn-dlB0ei4
   ✅ Success
77/260 Downloading: P2gW3SUSK78
   ✅ Success
78/260 Downloading: YZbVsMOmu-g
   ✅ Success
79/260 Downloading: iMiixFCflrA
   ✅ Success
80/260 Downloading: fn338PccJ_E
   ✅ Success
81/260 Downloading: UQ4Ebe2tgHs
   ✅ Success
82/260 Downloading: 8dGGk_RzXnc
   ✅ Success
83/260 Downloading: 416LXKQCpQg
   ❌ Failed
84/260 Downloading: 4Y5bkGtsKhQ
   ✅ Success
85/260 Downloading: aeDem1G2mYQ
   ✅ Success
86/260 Downloading: dr7qwPIK4-w
   ✅ Success
87/260 Downloading: yXrJzXwE0oI
   ✅ Success
88/260 Downloading: IoosP6XOZA0
   ✅ Success
89/260 Downloading: OlI2fmSWG8Y
   ❌ Failed
90/260 Downloading: 64AHuTLREwA
   ✅ Success
91/260 Downloading: qiz7W5D6gC8
   ✅ Success
92/260 Downloading: snHpxgH2LsA
   ✅ Success
93/260 Downloading: IxyLK6xKJx8
   ❌ Failed
94/260 Downloading: RJL0Lx2KcRw
   ✅ Success
95/260 Downloading: kmuqD8Th6Fg
   ❌ Failed
96/260 Downloading: j3rmCibPKT8
   ❌ Failed
97/260 Downloading: riTJvkfGgXs
   ✅ Success
98/260 Downloading: vUI_xLPuGyg
   ✅ Success
99/260 Downloading: 39SAZ_biV-M
   ✅ Success
100/260 Downloading: v7oHMNYHyCM
   ❌ Failed
101/260 Downloading: AVIaKgkjJf8
   ✅ Success
102/260 Downloading: V0H1J5Umung
   ✅ Success
103/260 Downloading: 660AJ1w2pJ8
   ✅ Success
104/260 Downloading: 7jaYSwfqXyo
   ✅ Success
105/260 Downloading: 4EbnQaqBUnw
   ✅ Success
106/260 Downloading: DurNF2CeVCU
   ❌ Failed
107/260 Downloading: NzYpRtkqZj4
   ❌ Failed
108/260 Downloading: wW5ule5SMYY
   ❌ Failed
109/260 Downloading: E8uP94MIcgs
   ✅ Success
110/260 Downloading: P6nnNLrOQDA
   ✅ Success
111/260 Downloading: UKUs82k3ZDg
   ❌ Failed
112/260 Downloading: b6mpHUSkt7Q
   ❌ Failed
113/260 Downloading: 5DNmaYCRFGc
   ✅ Success
114/260 Downloading: -wMFgnGcIms
   ✅ Success
115/260 Downloading: t4POpKL5wVA
   ✅ Success
116/260 Downloading: 7HII0xcclAQ
   ✅ Success
117/260 Downloading: bkONnNO9C30
   ❌ Failed
118/260 Downloading: y-XEIcHUVJM
   ✅ Success
119/260 Downloading: E8wij2OkxyQ
   ✅ Success
120/260 Downloading: GA_xfkTgdnU
   ✅ Success
121/260 Downloading: M-Ca-W-kvVU
   ❌ Failed
122/260 Downloading: Ql6A_GMX6E4
   ✅ Success
123/260 Downloading: 7eC-wuYuebE
   ✅ Success
124/260 Downloading: t2DVnwJammg
   ✅ Success
125/260 Downloading: EB4nlpvvIqc
   ✅ Success
126/260 Downloading: H5x4vclZM8o
   ✅ Success
127/260 Downloading: qwTwLLs_FrQ
   ✅ Success
128/260 Downloading: 1v8tkB9u7DI
   ❌ Failed
129/260 Downloading: HujVRxj3Cbc
   ✅ Success
130/260 Downloading: d1rRFwjP5fk
   ✅ Success
131/260 Downloading: yU7EWclY4eQ
   ✅ Success
132/260 Downloading: K96-WN25Kfk
   ✅ Success
133/260 Downloading: 4t7ohAt0REk
   ❌ Failed
134/260 Downloading: qWqg01YJF_Y
   ✅ Success
135/260 Downloading: KVSIOOeEUaU
   ✅ Success
136/260 Downloading: aCTxA_O_g8I
   ❌ Failed
137/260 Downloading: qPTwqnfPQvA
   ❌ Failed
138/260 Downloading: LtWMvzRYgzw
   ✅ Success
139/260 Downloading: vBWYA_Pawvw
   ✅ Success
140/260 Downloading: S_4v4qM9aMc
   ✅ Success
141/260 Downloading: ECYSO3nGPTI
   ✅ Success
142/260 Downloading: cScLM6Xp2JI
   ✅ Success
143/260 Downloading: YN2pWQATSbs
   ❌ Failed
144/260 Downloading: F6i5H9my_mg
   ✅ Success
145/260 Downloading: -mDOld5RYxw
   ✅ Success
146/260 Downloading: X6yjmPJUowI
   ❌ Failed
147/260 Downloading: 6QebKObX1Ak
   ✅ Success
148/260 Downloading: MUksgxwsiKE
   ❌ Failed
149/260 Downloading: c6d3C4d_POY
   ❌ Failed
150/260 Downloading: ce_EfI1iIfg
   ✅ Success
151/260 Downloading: loDwJXeyFsk
   ✅ Success
152/260 Downloading: -E9o4ywIoj8
   ❌ Failed
153/260 Downloading: u3Bb1hWztDM
   ❌ Failed
154/260 Downloading: xpu2AcRFbMg
   ✅ Success
155/260 Downloading: rQP0RsslgKg
   ✅ Success
156/260 Downloading: i9jrT01rRHI
   ✅ Success
157/260 Downloading: zwYTcyF2zMQ
   ✅ Success
158/260 Downloading: ufZUXUHlhu0
   ❌ Failed
159/260 Downloading: auOZa1JEjIA
   ✅ Success
160/260 Downloading: o5ykwLDoRpE
   ✅ Success
161/260 Downloading: Hkltdxt_xt0
   ✅ Success
162/260 Downloading: k5c_pkt45Fk
   ❌ Failed
163/260 Downloading: MeI4ni_Ub-8
   ✅ Success
164/260 Downloading: Nbmc0U5HPl0
   ✅ Success
165/260 Downloading: RLhQfM6QDis
   ✅ Success
166/260 Downloading: 4iYEmP6r4J8
   ✅ Success
167/260 Downloading: 9bxrcu7lY1s
   ✅ Success
168/260 Downloading: NthIhmXQHM4
   ✅ Success
169/260 Downloading: QOm6SG_Iq_I
   ✅ Success
170/260 Downloading: VTvozFyB-qg
   ✅ Success
171/260 Downloading: LRJtF3goIMM
   ✅ Success
172/260 Downloading: s5qcTYTYwww
   ✅ Success
173/260 Downloading: 8VPsFZg6E54
   ✅ Success
174/260 Downloading: QNiBnMlfT2U
   ✅ Success
175/260 Downloading: EXgFZCBZ18Y
   ✅ Success
176/260 Downloading: nAAQBbij7D4
   ✅ Success
177/260 Downloading: 3ComHEFnxpQ
   ✅ Success
178/260 Downloading: thE9hiWy9IU
   ✅ Success
179/260 Downloading: j3iMh-oNplg
   ✅ Success
180/260 Downloading: h9oEGPGf1ew
   ✅ Success
181/260 Downloading: m1we0tQ3YFo
   ✅ Success
182/260 Downloading: c8CwGE0y-to
   ✅ Success
183/260 Downloading: DUfww-VAuFI
   ✅ Success
184/260 Downloading: sXwmS5IPE_s
   ✅ Success
185/260 Downloading: qWxvvNXnfFU
   ✅ Success
186/260 Downloading: 3Q4wpIZjUzo
   ❌ Failed
187/260 Downloading: mBHpBWlswqE
   ✅ Success
188/260 Downloading: kzpGjp1ynEg
   ✅ Success
189/260 Downloading: UgHi6OHhmoI
   ❌ Failed
190/260 Downloading: ikHblCcDjo4
   ✅ Success
191/260 Downloading: Vp2BsPfQF-A
   ✅ Success
192/260 Downloading: VK9uFm_fj9g
   ✅ Success
193/260 Downloading: GucKN7PEswA
   ✅ Success
194/260 Downloading: haNJK8fNNzw
   ✅ Success
195/260 Downloading: fvWTVXCuwjo
   ❌ Failed
196/260 Downloading: 5OqotgPe39E
   ✅ Success
197/260 Downloading: mX1ZQyiwUhw
   ✅ Success
198/260 Downloading: C7L3sp5qcc8
   ❌ Failed
199/260 Downloading: ysz-iYt9pB8
   ✅ Success
200/260 Downloading: lp_btlebwc4
   ✅ Success
201/260 Downloading: JgdspFz2kOI
   ✅ Success
202/260 Downloading: Ad0rGygHe4g
   ❌ Failed
203/260 Downloading: 3rky5IrE0L8
   ✅ Success
204/260 Downloading: bSlXuZCoQQQ
   ❌ Failed
205/260 Downloading: 8Uum8xLtpJI
   ✅ Success
206/260 Downloading: 2_YKXWzK_e4
   ❌ Failed
207/260 Downloading: 3vY9TXRwM_c
   ✅ Success
208/260 Downloading: qXrB4bBoMjs
   ✅ Success
209/260 Downloading: OToAhZjp22s
   ✅ Success
210/260 Downloading: VuOlfnYwy3s
   ✅ Success
211/260 Downloading: wKVoF9NBd-U
   ✅ Success
212/260 Downloading: 8YI0dt-GKPY
   ❌ Failed
213/260 Downloading: 4vLL7INP0VE
   ✅ Success
214/260 Downloading: B0eaCPauYQI
   ✅ Success
215/260 Downloading: ArfpBVgOf3o
   ✅ Success
216/260 Downloading: 1sxdvU7LFvQ
   ✅ Success
217/260 Downloading: W6ST7oYkjWk
   ✅ Success
218/260 Downloading: CoXEVTDJI-k
   ✅ Success
219/260 Downloading: GOtmAPjCWRA
   ✅ Success
220/260 Downloading: bgSZodzLNaQ
   ✅ Success
221/260 Downloading: t_ZXMjlAj-Y
   ✅ Success
222/260 Downloading: 8clWo2RKdZI
   ✅ Success
223/260 Downloading: nVA8BdFZM7k
   ✅ Success
224/260 Downloading: L_0W4TfWwNY
   ✅ Success
225/260 Downloading: 8nn9_3rjlcE
   ✅ Success
226/260 Downloading: XwTzGSMIJsY
   ✅ Success
227/260 Downloading: -a9xYse4q-Y
   ✅ Success
228/260 Downloading: tPnQVfR2pk0
   ❌ Failed
229/260 Downloading: vdP-yuw2b0s
   ✅ Success
230/260 Downloading: 47g5m1VJc60
   ✅ Success
231/260 Downloading: wYf6cMWiEQw
   ✅ Success
232/260 Downloading: KNQFi3nHzHI
   ✅ Success
233/260 Downloading: 9Dci2M4yKHE
   ✅ Success
234/260 Downloading: Jmt9zdbpXhg
   ✅ Success
235/260 Downloading: G7STEcMSM5s
   ✅ Success
236/260 Downloading: FD_AHY-4uaA
   ✅ Success
237/260 Downloading: W9aT6tHnFko
   ✅ Success
238/260 Downloading: QHoilZkGhD0
   ✅ Success
239/260 Downloading: 8Uza2J26VnE
   ✅ Success
240/260 Downloading: PuM-No5a2rA
   ✅ Success
241/260 Downloading: SA0tLDhr3eY
   ✅ Success
242/260 Downloading: c30PHNAX7Gc
   ❌ Failed
243/260 Downloading: v6qZ8SZHVBw
   ❌ Failed
244/260 Downloading: ULMWqKxEmMQ
   ✅ Success
245/260 Downloading: 2VzvCtRDom8
   ✅ Success
246/260 Downloading: ZWvESjqRN-E
   ✅ Success
247/260 Downloading: 6px4xc_olnE
   ✅ Success
248/260 Downloading: Nh1ucbQ2EHY
   ✅ Success
249/260 Downloading: 3EZkxpDYBdE
   ✅ Success
250/260 Downloading: HQMK2A-_iRI
   ❌ Failed
251/260 Downloading: YCoWHIEAlOs
   ✅ Success
252/260 Downloading: kamIbZVN0Mk
   ✅ Success
253/260 Downloading: FRpa8M_jNgA
   ✅ Success
254/260 Downloading: EWP18lDMrwM
   ✅ Success
255/260 Downloading: iMQ1K2V9x4k
   ✅ Success
256/260 Downloading: N1UHiTCPRyI
   ✅ Success
257/260 Downloading: 14ZZavlJFGE
   ✅ Success
258/260 Downloading: yGuifXK86bE
   ✅ Success
259/260 Downloading: NyT8rRl6nd8
   ✅ Success
260/260 Downloading: OfSYUsdgcBE
   ✅ Success

==============================
FIRE ALARM DOWNLOAD COMPLETE
==============================
Successful: 207
Already existed: 0
Failed: 53
Results saved to: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata/fire_alarm_download_results.csv

In [31]:
# Get Smoke Alarm candidates from AudioSet unbalanced metadata

smoke_alarm_id = label_ids["Smoke Alarm"]

smoke_alarm_rows = []

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        if smoke_alarm_id in labels:
            smoke_alarm_rows.append(row)

smoke_alarm_candidates = pd.DataFrame(
    smoke_alarm_rows,
    columns=["YTID", "start_seconds", "end_seconds", "positive_labels"]
)

smoke_alarm_candidates = smoke_alarm_candidates.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print("Unique Smoke Alarm candidates:", len(smoke_alarm_candidates))
display(smoke_alarm_candidates.head(10))

Unique Smoke Alarm candidates: 426

          YTID start_seconds end_seconds                  positive_labels
0  -EWgUW9lKes       210.000     220.000               /m/01y3hg,/m/09x0r
1  -fKLFmdZXiA        20.000      30.000                        /m/01y3hg
2  -uS-9D7njq4        40.000      50.000               /m/01y3hg,/m/09x0r
3  013tVBuTrkE        23.000      33.000                        /m/01y3hg
4  0Cs-KOQF9t0        40.000      50.000              /m/01y3hg,/m/0c3f7m
5  0FjMs2FWcbQ        30.000      40.000              /m/01y3hg,/m/03kmc9
6  0JFfTcAXT2Y        30.000      40.000     /m/01y3hg,/m/02fs_r,/m/09x0r
7  0VeDtKRDy1Q        30.000      40.000  /m/01y3hg,/m/07pp_mv,/t/dd00125
8  0ciZGU2_h6M         0.000      10.000             /m/01y3hg,/t/dd00125
9  0o0-GQj6Pow        10.000      20.000    /m/01y3hg,/m/07pp_mv,/m/09x0r

In [32]:
# Select Smoke Alarm download candidates

SMOKE_ALARM_TARGET = 260

smoke_alarm_download_candidates = smoke_alarm_candidates.sample(
    n=SMOKE_ALARM_TARGET,
    random_state=42
).reset_index(drop=True)

print("Smoke Alarm candidates selected:", len(smoke_alarm_download_candidates))
display(smoke_alarm_download_candidates.head(10))

Smoke Alarm candidates selected: 260

          YTID start_seconds end_seconds                positive_labels
0  yux_XsU7UI8       420.000     430.000             /m/01y3hg,/m/09x0r
1  8clWo2RKdZI        30.000      40.000  /m/01y3hg,/m/030rvx,/m/0c3f7m
2  ONWBTiUy4To       120.000     130.000             /m/01y3hg,/m/09x0r
3  3TMdvmGUWTs        30.000      40.000                      /m/01y3hg
4  oaMQwPpGuCs        20.000      30.000           /m/01y3hg,/t/dd00125
5  n5n-nCMLboQ        20.000      30.000                      /m/01y3hg
6  M-WbEEKI7cY         5.000      15.000             /m/01y3hg,/m/09x0r
7  LpqJtM4eA9E        20.000      30.000                      /m/01y3hg
8  yQIdLf3BEL8       130.000     140.000           /m/01y3hg,/t/dd00126
9  M6eLjTo2jqQ        10.000      20.000                      /m/01y3hg

In [33]:
# Download Smoke Alarm clips from YouTube

import subprocess
import os
import time
import pandas as pd

smoke_alarm_folder = os.path.join(BASE_DIR, "Smoke Alarm")
os.makedirs(smoke_alarm_folder, exist_ok=True)

results = []

for i, row in smoke_alarm_download_candidates.iterrows():

    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        smoke_alarm_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # If already downloaded, don't download again
    if os.path.exists(output_file):
        print(f"{i+1}/{len(smoke_alarm_download_candidates)} ✅ Already exists: {ytid}")

        results.append({
            "YTID": ytid,
            "start_seconds": start,
            "end_seconds": end,
            "label": "Smoke Alarm",
            "filename": output_file,
            "status": "already_exists"
        })
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(f"{i+1}/{len(smoke_alarm_download_candidates)} Downloading: {ytid}")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        status = "success"
        print("   ✅ Success")
    else:
        status = "failed"
        print("   ❌ Failed")

    results.append({
        "YTID": ytid,
        "start_seconds": start,
        "end_seconds": end,
        "label": "Smoke Alarm",
        "filename": output_file if status == "success" else "",
        "status": status
    })

    time.sleep(1)

# Save download results
smoke_alarm_download_results = pd.DataFrame(results)

results_path = os.path.join(
    METADATA_DIR,
    "smoke_alarm_download_results.csv"
)

smoke_alarm_download_results.to_csv(results_path, index=False)

print("\n==============================")
print("SMOKE ALARM DOWNLOAD COMPLETE")
print("==============================")
print("Successful:", (smoke_alarm_download_results["status"] == "success").sum())
print("Already existed:", (smoke_alarm_download_results["status"] == "already_exists").sum())
print("Failed:", (smoke_alarm_download_results["status"] == "failed").sum())
print("Results saved to:", results_path)

1/260 Downloading: yux_XsU7UI8
   ❌ Failed
2/260 Downloading: 8clWo2RKdZI
   ✅ Success
3/260 Downloading: ONWBTiUy4To
   ❌ Failed
4/260 Downloading: 3TMdvmGUWTs
   ✅ Success
5/260 Downloading: oaMQwPpGuCs
   ✅ Success
6/260 Downloading: n5n-nCMLboQ
   ❌ Failed
7/260 Downloading: M-WbEEKI7cY
   ❌ Failed
8/260 Downloading: LpqJtM4eA9E
   ❌ Failed
9/260 Downloading: yQIdLf3BEL8
   ✅ Success
10/260 Downloading: M6eLjTo2jqQ
   ✅ Success
11/260 Downloading: xV3w0q-EhvQ
   ❌ Failed
12/260 Downloading: 8JYVd2QFFN4
   ✅ Success
13/260 Downloading: RVoFRijuRdo
   ❌ Failed
14/260 Downloading: jS2Ud6bs4Pc
   ✅ Success
15/260 Downloading: 4TId8kDUeHQ
   ✅ Success
16/260 Downloading: JThDvQBA9m8
   ❌ Failed
17/260 Downloading: _uC0E6Wij4U
   ✅ Success
18/260 Downloading: 8QCztHe9QDM
   ❌ Failed
19/260 Downloading: 0o0-GQj6Pow
   ❌ Failed
20/260 Downloading: b7rGRMn-_ss
   ✅ Success
21/260 Downloading: c7DjT-J8Jeo
   ✅ Success
22/260 Downloading: Z3tJdZo4GZE
   ✅ Success
23/260 Downloading: PSelITJ2vzs
   ✅ Success
24/260 Downloading: 6Wb4uV4DXm4
   ✅ Success
25/260 Downloading: JPTBkETjuxc
   ✅ Success
26/260 Downloading: RAfqjEaDG0g
   ✅ Success
27/260 Downloading: KOauUYrIK40
   ✅ Success
28/260 Downloading: wwdVX5NjF44
   ✅ Success
29/260 Downloading: y2Vtor2sgGs
   ✅ Success
30/260 Downloading: ZwQxt4wbtGw
   ✅ Success
31/260 Downloading: GzdcXHqEThQ
   ❌ Failed
32/260 Downloading: YPEtGXY30Ow
   ✅ Success
33/260 Downloading: eAvmyu9TSx0
   ✅ Success
34/260 Downloading: B9RUAQn8_eQ
   ✅ Success
35/260 Downloading: zY3Z7NIiiE0
   ✅ Success
36/260 Downloading: 8p_OQNXymTc
   ❌ Failed
37/260 Downloading: lTnBd2ZuWuE
   ✅ Success
38/260 Downloading: g_ooq4WhytE
   ✅ Success
39/260 Downloading: hFfBqE3wtEk
   ❌ Failed
40/260 Downloading: zfI3S4Pgqg0
   ✅ Success
41/260 Downloading: UFi3hPJsAzY
   ✅ Success
42/260 Downloading: L455vziC_a0
   ❌ Failed
43/260 Downloading: 97-00Q8PovE
   ❌ Failed
44/260 Downloading: 8UP2-q5vPg0
   ❌ Failed
45/260 Downloading: 3kK9NzuMc5I
   ✅ Success
46/260 Downloading: EZCqTwek-nw
   ✅ Success
47/260 Downloading: dNuVh5U3S-c
   ❌ Failed
48/260 Downloading: 8nRp29GyvfM
   ✅ Success
49/260 Downloading: XClteeif6e8
   ✅ Success
50/260 Downloading: r2HUwUSAFnY
   ❌ Failed
51/260 Downloading: 1dVnP_e4gAQ
   ✅ Success
52/260 Downloading: VzerJLe2JJ4
   ✅ Success
53/260 Downloading: nYXcv0jWS_w
   ✅ Success
54/260 Downloading: -EWgUW9lKes
   ✅ Success
55/260 Downloading: 28onX7S1NoM
   ❌ Failed
56/260 Downloading: abowtShD9J8
   ✅ Success
57/260 Downloading: c1-9WDxRRFo
   ✅ Success
58/260 Downloading: 6YkMqL4nsJM
   ✅ Success
59/260 Downloading: kxlqvEqhvqg
   ✅ Success
60/260 Downloading: 9NPlvhz_OJg
   ✅ Success
61/260 Downloading: XPOzJe4yY-o
   ❌ Failed
62/260 Downloading: qUoSo0l0RlU
   ❌ Failed
63/260 Downloading: 9HLIXzPvUgE
   ✅ Success
64/260 Downloading: AYLHs63HqzA
   ❌ Failed
65/260 Downloading: ozxsvtGvsC0
   ❌ Failed
66/260 Downloading: 2ktJ9c53LpQ
   ✅ Success
67/260 Downloading: NurVkIihudk
   ✅ Success
68/260 Downloading: PAmNTUjc0G8
   ❌ Failed
69/260 Downloading: OBiVY-WotRc
   ✅ Success
70/260 Downloading: 4kDN9reeXT0
   ❌ Failed
71/260 Downloading: SvQMHBlYfLQ
   ✅ Success
72/260 Downloading: yJNIlzKCEfw
   ✅ Success
73/260 Downloading: C5QkOJqg7n4
   ✅ Success
74/260 Downloading: NIEXRkOlPJk
   ✅ Success
75/260 Downloading: yj9qTG8FN_w
   ✅ Success
76/260 Downloading: aeqor0OsgEo
   ❌ Failed
77/260 Downloading: 2NRDi8g-6Qk
   ✅ Success
78/260 Downloading: 5OqotgPe39E
   ✅ Success
79/260 Downloading: rKlEhIwEveg
   ✅ Success
80/260 Downloading: EGr1kjCw2zc
   ✅ Success
81/260 Downloading: B9XntQCc-CY
   ✅ Success
82/260 Downloading: rHUBojOMC_U
   ❌ Failed
83/260 Downloading: 6ZUkx7QysK8
   ✅ Success
84/260 Downloading: GrVcqid0Yqg
   ❌ Failed
85/260 Downloading: 2eqwsBYZ4lk
   ✅ Success
86/260 Downloading: 23xdTaTmoeI
   ✅ Success
87/260 Downloading: 7ieIuvHFbDw
   ✅ Success
88/260 Downloading: IHf52BfOqfE
   ✅ Success
89/260 Downloading: V2FuraJKqPI
   ✅ Success
90/260 Downloading: 3XuDG-w0NB8
   ✅ Success
91/260 Downloading: 9bxrcu7lY1s
   ✅ Success
92/260 Downloading: dCZ2RK2AXvA
   ❌ Failed
93/260 Downloading: TBRCGNMQoTg
   ✅ Success
94/260 Downloading: e84nCgFH7YI
   ✅ Success
95/260 Downloading: xx0wiWhWD-0
   ✅ Success
96/260 Downloading: XnADwIQO-VY
   ❌ Failed
97/260 Downloading: tPnQVfR2pk0
   ❌ Failed
98/260 Downloading: nbS7CJuv4pc
   ✅ Success
99/260 Downloading: 0FjMs2FWcbQ
   ❌ Failed
100/260 Downloading: 56T5s1843Wc
   ✅ Success
101/260 Downloading: db-TSWJBfpY
   ✅ Success
102/260 Downloading: M2Krl90_6hM
   ✅ Success
103/260 Downloading: qCb5DyebtgY
   ✅ Success
104/260 Downloading: w0vt3PrfpNE
   ❌ Failed
105/260 Downloading: 1xkIrZWnqMI
   ✅ Success
106/260 Downloading: vAFlySpK1iw
   ❌ Failed
107/260 Downloading: HzhA-Ir3PP4
   ✅ Success
108/260 Downloading: fG1MTPUKxyA
   ✅ Success
109/260 Downloading: 013tVBuTrkE
   ✅ Success
110/260 Downloading: 25psngPoZ7o
   ✅ Success
111/260 Downloading: icPBKqFUo_A
   ✅ Success
112/260 Downloading: 78Zjr9TBJkw
   ✅ Success
113/260 Downloading: SYk_wSGNc6M
   ✅ Success
114/260 Downloading: YCoWHIEAlOs
   ✅ Success
115/260 Downloading: 7KxyL-Jllnw
   ❌ Failed
116/260 Downloading: DW1Wkj72mGA
   ❌ Failed
117/260 Downloading: nRRjKdRX-Ko
   ✅ Success
118/260 Downloading: Rq6dML0xavA
   ✅ Success
119/260 Downloading: 3Q4wpIZjUzo
   ❌ Failed
120/260 Downloading: xFDZwe5DWTI
   ✅ Success
121/260 Downloading: SwvCrEDL0IA
   ✅ Success
122/260 Downloading: Sv3dZSK5qoA
   ✅ Success
123/260 Downloading: 2x-bngOE29o
   ❌ Failed
124/260 Downloading: 0VeDtKRDy1Q
   ❌ Failed
125/260 Downloading: i2vA57gUZAI
   ✅ Success
126/260 Downloading: e39O6phcY9Q
   ✅ Success
127/260 Downloading: D6-8ANtTbXA
   ✅ Success
128/260 Downloading: Bi-ZYLa6VcY
   ✅ Success
129/260 Downloading: YdYBcb_-ihU
   ✅ Success
130/260 Downloading: vmuHWr9tYA0
   ✅ Success
131/260 Downloading: EiRPg6qbpSo
   ✅ Success
132/260 Downloading: ETxXgrdZYoA
   ✅ Success
133/260 Downloading: IwHtO-PUesE
   ❌ Failed
134/260 Downloading: rBq1DO2glYw
   ❌ Failed
135/260 Downloading: cXqSnVsyR9g
   ✅ Success
136/260 Downloading: jwnHevAunrI
   ❌ Failed
137/260 Downloading: s6fBS-i3QZ4
   ✅ Success
138/260 Downloading: gCw4rzde2mg
   ✅ Success
139/260 Downloading: lVl9LR5OQp0
   ✅ Success
140/260 Downloading: LoG863LzdsM
   ❌ Failed
141/260 Downloading: t2DVnwJammg
   ✅ Success
142/260 Downloading: DIZzmPwXzfY
   ❌ Failed
143/260 Downloading: PFJ7yY9U_7A
   ✅ Success
144/260 Downloading: RSo_EFbrVtw
   ✅ Success
145/260 Downloading: tgOEC9-6fOA
   ✅ Success
146/260 Downloading: NbPmNpBBq1s
   ❌ Failed
147/260 Downloading: 9_xNgBdO1_g
   ✅ Success
148/260 Downloading: xFqA0foiO7g
   ❌ Failed
149/260 Downloading: rME75h7CxI4
   ✅ Success
150/260 Downloading: 8Uum8xLtpJI
   ✅ Success
151/260 Downloading: SJrnbMTgKg0
   ✅ Success
152/260 Downloading: Ek6oP8wxSOA
   ✅ Success
153/260 Downloading: V2ihYSr9MUA
   ❌ Failed
154/260 Downloading: kamIbZVN0Mk
   ✅ Success
155/260 Downloading: wfxil0p9Uw0
   ❌ Failed
156/260 Downloading: Wcu3nUmWr6A
   ❌ Failed
157/260 Downloading: o2Hp-n_nAEw
   ✅ Success
158/260 Downloading: kOfRBAucXV8
   ✅ Success
159/260 Downloading: NoxL_hQ5_oA
   ❌ Failed
160/260 Downloading: j3gPNQg2WpM
   ✅ Success
161/260 Downloading: fGN5_WdTY7A
   ✅ Success
162/260 Downloading: 4EbnQaqBUnw
   ✅ Success
163/260 Downloading: JM9hQsBcJ-4
   ❌ Failed
164/260 Downloading: g3eBrowsgs0
   ✅ Success
165/260 Downloading: OYjLr3BQaTs
   ✅ Success
166/260 Downloading: ziAGylX7qFo
   ✅ Success
167/260 Downloading: Vr0xaXAXC5U
   ✅ Success
168/260 Downloading: 73WLeECUDLI
   ✅ Success
169/260 Downloading: DjRo6s8n5qA
   ✅ Success
170/260 Downloading: zGqWGTVYYGk
   ✅ Success
171/260 Downloading: RwMSiW02zBk
   ✅ Success
172/260 Downloading: 0JFfTcAXT2Y
   ✅ Success
173/260 Downloading: fRrc-zniZ_c
   ✅ Success
174/260 Downloading: wwvwlXzOMEM
   ✅ Success
175/260 Downloading: MRHm-Z7jstg
   ✅ Success
176/260 Downloading: LAvzjP-geZg
   ✅ Success
177/260 Downloading: 0vGhtQkTMDA
   ✅ Success
178/260 Downloading: coLpDcqgNOs
   ❌ Failed
179/260 Downloading: BzpRN_aHn-0
   ✅ Success
180/260 Downloading: 9MqssX1p2gM
   ✅ Success
181/260 Downloading: ceXQQu2evEs
   ❌ Failed
182/260 Downloading: _WhuGYtGfNw
   ✅ Success
183/260 Downloading: NVw83w-oYYw
   ✅ Success
184/260 Downloading: wSVkxjMydrQ
   ❌ Failed
185/260 Downloading: XDRSkPiZef8
   ✅ Success
186/260 Downloading: XuTt61TkdzQ
   ✅ Success
187/260 Downloading: QW0LXEG4UjM
   ❌ Failed
188/260 Downloading: qf3OvE5ZtDI
   ✅ Success
189/260 Downloading: AQpmpzgr6cI
   ✅ Success
190/260 Downloading: UdNhJEJU9RU
   ✅ Success
191/260 Downloading: MnJBhjd_9sE
   ✅ Success
192/260 Downloading: RkH_-TYgMRk
   ✅ Success
193/260 Downloading: KdSI3jeQ86w
   ✅ Success
194/260 Downloading: -uS-9D7njq4
   ✅ Success
195/260 Downloading: B8-k1aA4tvw
   ✅ Success
196/260 Downloading: 7vlUS5GtTh4
   ❌ Failed
197/260 Downloading: VsfrkyVK5D0
   ❌ Failed
198/260 Downloading: GhKd7FGBqnA
   ❌ Failed
199/260 Downloading: BGXW2zRZOug
   ✅ Success
200/260 Downloading: K8glDhNlMYQ
   ✅ Success
201/260 Downloading: iGuoTBf4XyI
   ❌ Failed
202/260 Downloading: msCJ3dwWSOE
   ✅ Success
203/260 Downloading: BMhXVkAycMM
   ✅ Success
204/260 Downloading: ZizCKm2p2kY
   ✅ Success
205/260 Downloading: 7qicY9TPo_M
   ✅ Success
206/260 Downloading: 2OJGsYJ4LhM
   ✅ Success
207/260 Downloading: 4N7cWRe1o_M
   ❌ Failed
208/260 Downloading: KG872oPU5v8
   ✅ Success
209/260 Downloading: GgTEnuzP6uA
   ✅ Success
210/260 Downloading: _Se78wWT1no
   ❌ Failed
211/260 Downloading: SBu3AIxkVDQ
   ✅ Success
212/260 Downloading: PLMkwNLI7as
   ✅ Success
213/260 Downloading: 7mScDfYXRVI
   ✅ Success
214/260 Downloading: Xo-8TFdOzf4
   ✅ Success
215/260 Downloading: oF-9Fcjs5K0
   ✅ Success
216/260 Downloading: XzKP2q6WPMU
   ✅ Success
217/260 Downloading: vUI_xLPuGyg
   ✅ Success
218/260 Downloading: l5CEprbZ0OE
   ✅ Success
219/260 Downloading: VSVZVvhjv5A
   ✅ Success
220/260 Downloading: Gt_Hy1xVMn0
   ✅ Success
221/260 Downloading: KVLP3U6D6FE
   ❌ Failed
222/260 Downloading: s5VvgPLkqTg
   ✅ Success
223/260 Downloading: 9vaPgmB2cwY
   ✅ Success
224/260 Downloading: ok4A2lGB_hM
   ✅ Success
225/260 Downloading: U_YNGkCQ8bQ
   ✅ Success
226/260 Downloading: vRZmRfTxk1o
   ✅ Success
227/260 Downloading: ouY3LNgnjCA
   ✅ Success
228/260 Downloading: WYOkw22pRYU
   ✅ Success
229/260 Downloading: brzab0nsZQs
   ✅ Success
230/260 Downloading: iFH_A0_i8VY
   ✅ Success
231/260 Downloading: PQMwAnCaGiE
   ✅ Success
232/260 Downloading: Yfx69eTiVSc
   ✅ Success
233/260 Downloading: eSlzowm0I94
   ✅ Success
234/260 Downloading: wYrMd5pCHqQ
   ✅ Success
235/260 Downloading: eHOKqIoFvdI
   ✅ Success
236/260 Downloading: HkvuyG2OTOY
   ✅ Success
237/260 Downloading: 4Qlpx4p-iXU
   ✅ Success
238/260 Downloading: 0zTV4lhqXpA
   ✅ Success
239/260 Downloading: i1vFjX74XME
   ✅ Success
240/260 Downloading: Pd5Ub_tFci8
   ✅ Success
241/260 Downloading: cyOhUps9T8A
   ✅ Success
242/260 Downloading: aQDVR-L8JhQ
   ❌ Failed
243/260 Downloading: E6C-3XVCmfk
   ✅ Success
244/260 Downloading: OtoBeBD-zcQ
   ✅ Success
245/260 Downloading: soyoOKpa5Ag
   ✅ Success
246/260 Downloading: o6leDJX-xWc
   ✅ Success
247/260 Downloading: cpteHvyy0IA
   ✅ Success
248/260 Downloading: bvRTmLsmNl0
   ✅ Success
249/260 Downloading: EgSlyxBtnPg
   ✅ Success
250/260 Downloading: uyjm4ZROdgI
   ✅ Success
251/260 Downloading: wzylR_m_Ppg
   ✅ Success
252/260 Downloading: xiB5kCd0Dyk
   ✅ Success
253/260 Downloading: sP1Z-CPJfmM
   ✅ Success
254/260 Downloading: W_HhkSI07ms
   ✅ Success
255/260 Downloading: taJofmujGgw
   ✅ Success
256/260 Downloading: q-oRnt6ANq8
   ✅ Success
257/260 Downloading: N4QzDWQEhYE
   ✅ Success
258/260 Downloading: IszNI9-3vKI
   ❌ Failed
259/260 Downloading: RlwIW_OAvns
   ✅ Success
260/260 Downloading: ZDxoinMcZj0
   ✅ Success

==============================
SMOKE ALARM DOWNLOAD COMPLETE
==============================
Successful: 196
Already existed: 0
Failed: 64
Results saved to: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata/smoke_alarm_download_results.csv