In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

BASE_DIR = "/content/drive/MyDrive/SafeCue Audio Recordings"

print("Folder exists:", os.path.exists(BASE_DIR))
print("\nContents:")

for item in os.listdir(BASE_DIR):
    print( item)

Folder exists: True

Contents:
Siren
Fire Alarm
Smoke Alarm
Screaming
Background Noise

In [4]:
!pip install -q yt-dlp
!apt-get -qq update
!apt-get -qq install ffmpeg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.7/183.7 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 30.3 MB/s eta 0:00:00
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)

In [5]:
import os

METADATA_DIR = os.path.join(BASE_DIR, "_metadata")
os.makedirs(METADATA_DIR, exist_ok=True)

print("Metadata folder:", METADATA_DIR)

Metadata folder: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata

In [6]:
import pandas as pd

metadata_url = "https://research.google.com/audioset/download.html"

print("AudioSet metadata page:")
print(metadata_url)

AudioSet metadata page:
https://research.google.com/audioset/download.html

In [7]:
!wget -q --show-progress \
"https://huggingface.co/datasets/agkphysics/AudioSet/resolve/main/balanced_train_segments.csv" \
-o /dev/null

In [8]:
import os

print(os.listdir(METADATA_DIR))

[]

In [9]:
import requests

url = "https://research.google.com/audioset/download.html"
response = requests.get(url)

print("Status code:", response.status_code)
print("Page downloaded:", len(response.text) > 0)

Status code: 200
Page downloaded: True

In [10]:
import requests

url = "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/balanced_train_segments.csv"

output_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

response = requests.get(url)

with open(output_path, "wb") as f:
    f.write(response.content)

print("Downloaded:", output_path)
print("File size:", os.path.getsize(output_path), "bytes")

Downloaded: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata/balanced_train_segments.csv
File size: 1211931 bytes

In [14]:
csv_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

with open(csv_path, "r", encoding="utf-8") as f:
    for i in range(8):
        print(f"LINE {i+1}:", repr(f.readline()))

LINE 1: '# Segments csv created Sun Mar  5 10:54:31 2017\n'
LINE 2: '# num_ytids=22160, num_segs=22160, num_unique_labels=527, num_positive_labels=52882\n'
LINE 3: '# YTID, start_seconds, end_seconds, positive_labels\n'
LINE 4: '--PJHxphWEs, 30.000, 40.000, "/m/09x0r,/t/dd00088"\n'
LINE 5: '--ZhevVpy1s, 50.000, 60.000, "/m/012xff"\n'
LINE 6: '--aE2O5G5WE, 0.000, 10.000, "/m/03fwl,/m/04rlf,/m/09x0r"\n'
LINE 7: '--aO5cdqSAg, 30.000, 40.000, "/t/dd00003,/t/dd00005"\n'
LINE 8: '--aaILOrkII, 200.000, 210.000, "/m/032s66,/m/073cg4"\n'

In [15]:
import csv
import pandas as pd
import os

csv_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

rows = []

with open(csv_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if row and not row[0].startswith("#"):
            rows.append(row)

df = pd.DataFrame(
    rows,
    columns=["YTID", "start_seconds", "end_seconds", "positive_labels"]
)

print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Shape: (22160, 4)

First 5 rows:

          YTID start_seconds end_seconds             positive_labels
0  --PJHxphWEs        30.000      40.000         /m/09x0r,/t/dd00088
1  --ZhevVpy1s        50.000      60.000                   /m/012xff
2  --aE2O5G5WE         0.000      10.000  /m/03fwl,/m/04rlf,/m/09x0r
3  --aO5cdqSAg        30.000      40.000       /t/dd00003,/t/dd00005
4  --aaILOrkII       200.000     210.000         /m/032s66,/m/073cg4

In [16]:
import requests
import json
import os

ontology_url = "https://raw.githubusercontent.com/audioset/ontology/master/ontology.json"
ontology_path = os.path.join(METADATA_DIR, "ontology.json")

response = requests.get(ontology_url)
response.raise_for_status()

with open(ontology_path, "wb") as f:
    f.write(response.content)

print("Ontology downloaded successfully!")
print("File size:", os.path.getsize(ontology_path), "bytes")

Ontology downloaded successfully!
File size: 342780 bytes

In [17]:
import json

with open(ontology_path, "r", encoding="utf-8") as f:
    ontology = json.load(f)

keywords = ["siren", "fire alarm", "smoke alarm", "screaming", "background noise"]

for keyword in keywords:
    print(f"\n=== {keyword.upper()} ===")

    matches = []
    for item in ontology:
        name = item.get("name", "")
        if keyword.lower() in name.lower():
            matches.append((item.get("id"), name))

    for audio_id, name in matches:
        print(audio_id, "→", name)

=== SIREN ===
/m/04qvtq → Police car (siren)
/m/012n7d → Ambulance (siren)
/m/012ndj → Fire engine, fire truck (siren)
/m/03kmc9 → Siren
/m/0dgbq → Civil defense siren

=== FIRE ALARM ===
/m/0c3f7m → Fire alarm

=== SMOKE ALARM ===
/m/01y3hg → Smoke detector, smoke alarm

=== SCREAMING ===
/m/03qc9zr → Screaming

=== BACKGROUND NOISE ===
/m/093_4n → Background noise

In [18]:
label_ids = {
    "Siren": "/m/03kmc9",
    "Fire Alarm": "/m/0c3f7m",
    "Smoke Alarm": "/m/01y3hg",
    "Screaming": "/m/03qc9zr",
    "Background Noise": "/m/093_4n"
}

for category, label_id in label_ids.items():
    count = df["positive_labels"].apply(
        lambda x: label_id in x.split(",")
    ).sum()

    print(f"{category}: {count} clips")

Siren: 207 clips
Fire Alarm: 60 clips
Smoke Alarm: 60 clips
Screaming: 59 clips
Background Noise: 0 clips

In [19]:
import requests
import os

url = "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/unbalanced_train_segments.csv"

output_path = os.path.join(METADATA_DIR, "unbalanced_train_segments.csv")

response = requests.get(url)
response.raise_for_status()

with open(output_path, "wb") as f:
    f.write(response.content)

print("Downloaded successfully!")
print("File size:", os.path.getsize(output_path), "bytes")

Downloaded successfully!
File size: 101468408 bytes

In [20]:
import csv
from collections import Counter

unbalanced_path = os.path.join(
    METADATA_DIR,
    "unbalanced_train_segments.csv"
)

counts = Counter()

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        for category, label_id in label_ids.items():
            if label_id in labels:
                counts[category] += 1

print("AudioSet unbalanced training counts:")
for category in label_ids:
    print(f"{category}: {counts[category]} clips")

AudioSet unbalanced training counts:
Siren: 8079 clips
Fire Alarm: 801 clips
Smoke Alarm: 426 clips
Screaming: 1126 clips
Background Noise: 0 clips

In [21]:
siren_id = "/m/03kmc9"

siren_rows = df[
    df["positive_labels"].apply(
        lambda x: siren_id in x.split(",")
    )
].reset_index(drop=True)

print("Siren clips available:", len(siren_rows))
print("\nFirst Siren clip:")
display(siren_rows.head(1))

Siren clips available: 207

First Siren clip:

,YTID,start_seconds,end_seconds,positive_labels
0,-4RWqM0UCCY,0.000,10.000,"/m/012n7d,/m/02mfyn,/m/03j1ly,/m/03kmc9"

In [23]:
import subprocess
import os
import time

# Number of clips to test
NUM_TEST = 10

# Use the first 10 Siren clips
test_rows = siren_rows.head(NUM_TEST)

siren_folder = os.path.join(BASE_DIR, "Siren")
os.makedirs(siren_folder, exist_ok=True)

success = 0
failed = 0

for i, row in test_rows.iterrows():
    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        siren_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # Skip if already downloaded
    if os.path.exists(output_file):
        print(f"Already exists: {ytid}")
        success += 1
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(f"Downloading {success + failed + 1}/{NUM_TEST}: {ytid}")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        success += 1
        print("  ✅ Success")
    else:
        failed += 1
        print("  ❌ Failed")

    time.sleep(1)

print("\n====================")
print("DOWNLOAD TEST COMPLETE")
print("====================")
print("Successful:", success)
print("Failed:", failed)

Already exists: -4RWqM0UCCY
Downloading 2/10: -Y1qiiugnk8
  ✅ Success
Downloading 3/10: -_dElQcyJnA
  ✅ Success
Downloading 4/10: -gKNRXbpAKs
  ✅ Success
Downloading 5/10: -oSw8wNpLcY
  ✅ Success
Downloading 6/10: -z47zN0YyE4
  ✅ Success
Downloading 7/10: 03NLMEMi8-I
  ✅ Success
Downloading 8/10: 0JKcTVpby0I
  ✅ Success
Downloading 9/10: 0JPT13OUVV8
  ✅ Success
Downloading 10/10: 0PhU-PIsUMw
  ✅ Success

====================
DOWNLOAD TEST COMPLETE
====================
Successful: 10
Failed: 0

In [24]:
# Create a list of unique Siren YouTube sources
# We will use this list for the larger download.

siren_candidates = siren_rows.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print("Total Siren candidates:", len(siren_candidates))
print("\nFirst 10 candidates:")
display(siren_candidates.head(10))

Total Siren candidates: 207

First 10 candidates:

,YTID,start_seconds,end_seconds,positive_labels
0,-4RWqM0UCCY,0.000,10.000,"/m/012n7d,/m/02mfyn,/m/03j1ly,/m/03kmc9"
1,-Y1qiiugnk8,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9"
2,-_dElQcyJnA,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9,/m/04qvtq"
3,-gKNRXbpAKs,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9,/m/0dgbq"
4,-oSw8wNpLcY,60.000,70.000,"/m/030rvx,/m/03kmc9"
5,-z47zN0YyE4,420.000,430.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
6,03NLMEMi8-I,30.000,40.000,"/m/03kmc9,/m/0dgbq"
7,0JKcTVpby0I,30.000,40.000,"/m/03kmc9,/m/0dgbq"
8,0JPT13OUVV8,220.000,230.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
9,0PhU-PIsUMw,80.000,90.000,"/m/03kmc9,/m/0dgbq"

In [25]:
import csv
import pandas as pd
import os

unbalanced_path = os.path.join(
    METADATA_DIR,
    "unbalanced_train_segments.csv"
)

siren_id = "/m/03kmc9"

siren_unbalanced_rows = []

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        if siren_id in labels:
            siren_unbalanced_rows.append(row)

siren_unbalanced = pd.DataFrame(
    siren_unbalanced_rows,
    columns=["YTID", "start_seconds", "end_seconds", "positive_labels"]
)

# Remove duplicate YouTube videos
siren_unbalanced = siren_unbalanced.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print("Unique Siren candidates in unbalanced set:", len(siren_unbalanced))
display(siren_unbalanced.head(10))

Unique Siren candidates in unbalanced set: 8079

,YTID,start_seconds,end_seconds,positive_labels
0,--7T50tAIrg,6.000,16.000,"/m/03kmc9,/m/09x0r"
1,-09rxiqNNEs,30.000,40.000,"/m/03kmc9,/m/0dgbq"
2,-0Eem_FuIto,15.000,25.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
3,-122tCXtFhU,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq,/m/07yv9,/m/0k4j"
4,-2GlU3e0nTU,170.000,180.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"
5,-34Lznw_wUA,10.000,20.000,/m/03kmc9
6,-3qh-WFUV2U,30.000,40.000,"/m/03kmc9,/m/0dgbq"
7,-4JG_Ag99hY,30.000,40.000,"/m/03kmc9,/m/0dgbq"
8,-5EiLqHCLuI,0.000,10.000,"/m/012n7d,/m/03j1ly,/m/03kmc9"
9,-5o4C4ZtHSU,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"

In [26]:
# Select 260 Siren candidates for downloading
# We use a fixed random seed so the selection is reproducible.

SIREN_TARGET = 260

siren_download_candidates = siren_unbalanced.sample(
    n=SIREN_TARGET,
    random_state=42
).reset_index(drop=True)

print("Siren candidates selected:", len(siren_download_candidates))

display(siren_download_candidates.head(10))

Siren candidates selected: 260

,YTID,start_seconds,end_seconds,positive_labels
0,JngI6xTRE2o,30.000,40.000,"/m/012n7d,/m/03j1ly,/m/03kmc9,/m/04qvtq"
1,uaFJj5A9jCE,2.000,12.000,"/m/012ndj,/m/03j1ly,/m/03kmc9"
2,w8IVfFqEXjw,60.000,70.000,"/m/03kmc9,/m/0dgbq"
3,ysJhEu_L7lc,30.000,40.000,/m/03kmc9
4,r-ww2qIp1BE,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"
5,NHcHQ6ptBmA,30.000,40.000,/m/03kmc9
6,ctyG4PM_rtw,0.000,10.000,"/m/0342h,/m/03kmc9,/m/04szw,/m/0fx80y"
7,azXoLk-FCrU,30.000,40.000,"/m/03kmc9,/m/04qvtq,/m/07yv9"
8,CiYGv42LsZ8,28.000,38.000,"/m/03kmc9,/m/07yv9,/m/0k4j"
9,axOkcNpjyb4,30.000,40.000,"/m/03j1ly,/m/03kmc9,/m/04qvtq"

In [27]:
import subprocess
import os
import time
import pandas as pd

siren_folder = os.path.join(BASE_DIR, "Siren")
os.makedirs(siren_folder, exist_ok=True)

results = []

for i, row in siren_download_candidates.iterrows():

    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        siren_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # If already downloaded, don't download again
    if os.path.exists(output_file):
        print(f"{i+1}/{len(siren_download_candidates)} ✅ Already exists: {ytid}")

        results.append({
            "YTID": ytid,
            "start_seconds": start,
            "end_seconds": end,
            "label": "Siren",
            "filename": output_file,
            "status": "already_exists"
        })
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(f"{i+1}/{len(siren_download_candidates)} Downloading: {ytid}")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        status = "success"
        print("   ✅ Success")
    else:
        status = "failed"
        print("   ❌ Failed")

    results.append({
        "YTID": ytid,
        "start_seconds": start,
        "end_seconds": end,
        "label": "Siren",
        "filename": output_file if status == "success" else "",
        "status": status
    })

    time.sleep(1)

# Save download results
download_results = pd.DataFrame(results)

results_path = os.path.join(
    METADATA_DIR,
    "siren_download_results.csv"
)

download_results.to_csv(results_path, index=False)

print("\n==============================")
print("SIREN DOWNLOAD COMPLETE")
print("==============================")
print("Successful:", (download_results["status"] == "success").sum())
print("Already existed:", (download_results["status"] == "already_exists").sum())
print("Failed:", (download_results["status"] == "failed").sum())
print("Results saved to:", results_path)

1/260 Downloading: JngI6xTRE2o
   ✅ Success
2/260 Downloading: uaFJj5A9jCE
   ✅ Success
3/260 Downloading: w8IVfFqEXjw
   ✅ Success
4/260 Downloading: ysJhEu_L7lc
   ✅ Success
5/260 Downloading: r-ww2qIp1BE
   ❌ Failed
6/260 Downloading: NHcHQ6ptBmA
   ✅ Success
7/260 Downloading: ctyG4PM_rtw
   ✅ Success
8/260 Downloading: azXoLk-FCrU
   ✅ Success
9/260 Downloading: CiYGv42LsZ8
   ✅ Success
10/260 Downloading: axOkcNpjyb4
   ✅ Success
11/260 Downloading: 1Q61oRUkfC0
   ✅ Success
12/260 Downloading: Lg6yI5szlVw
   ✅ Success
13/260 Downloading: yDeuZ92Y0eQ
   ✅ Success
14/260 Downloading: 2iKT4cvbJy8
   ❌ Failed
15/260 Downloading: 3LblLgNthRs
   ✅ Success
16/260 Downloading: FF410bQhJ8s
   ✅ Success
17/260 Downloading: HWeSf6Dsa5g
   ✅ Success
18/260 Downloading: 79-rErKgp3s
   ✅ Success
19/260 Downloading: vVEpMHmcH5Q
   ✅ Success
20/260 Downloading: eRZyNpT-XB8
   ✅ Success
21/260 Downloading: lAyZQxneqGA
   ✅ Success
22/260 Downloading: 0rdPzsSkzOU
   ✅ Success
23/260 Downloading: 0vKWXrc8PZo
   ❌ Failed
24/260 Downloading: E__SrkG0dvQ
   ✅ Success
25/260 Downloading: y8LYuwp5g-Y
   ✅ Success
26/260 Downloading: eY7_EkQ84UI
   ✅ Success
27/260 Downloading: WtzkncVLdKA
   ✅ Success
28/260 Downloading: 5OrXB62YfqY
   ✅ Success
29/260 Downloading: _mtDau5zA5k
   ❌ Failed
30/260 Downloading: JxIFYhhW1yw
   ✅ Success
31/260 Downloading: VC0vIx1a6Xg
   ✅ Success
32/260 Downloading: f_tW6gPPxrc
   ✅ Success
33/260 Downloading: 1d7RTWiSszo
   ✅ Success
34/260 Downloading: T9YB50TPbNQ
   ✅ Success
35/260 Downloading: lGqGGqSt784
   ✅ Success
36/260 Downloading: KBBzBNojAzM
   ✅ Success
37/260 Downloading: m4FXx4DA6CM
   ✅ Success
38/260 Downloading: lrMU3eGqw8A
   ✅ Success
39/260 Downloading: FrUZ9YYDzNY
   ✅ Success
40/260 Downloading: 9dLUJRQELfk
   ✅ Success
41/260 Downloading: hoIiES5qHHU
   ✅ Success
42/260 Downloading: djG_6S2I_EQ
   ✅ Success
43/260 Downloading: eD7bF8jdDzk
   ✅ Success
44/260 Downloading: IPRSfGhKCk4
   ✅ Success
45/260 Downloading: 1SGSVCCovqs
   ❌ Failed
46/260 Downloading: P0rf0FeDuSo
   ✅ Success
47/260 Downloading: KvoVUZQ9520
   ✅ Success
48/260 Downloading: IyUIHp3z7o4
   ✅ Success
49/260 Downloading: RbCskQNDntc
   ✅ Success
50/260 Downloading: N4d41fjHTd8
   ✅ Success
51/260 Downloading: uIwIEhjXhp0
   ❌ Failed
52/260 Downloading: wiWtK8SnXeE
   ✅ Success
53/260 Downloading: m-krD26VgMc
   ✅ Success
54/260 Downloading: VpVQSzhSd14
   ✅ Success
55/260 Downloading: VeCP6mZbbCQ
   ✅ Success
56/260 Downloading: qSwc-5_tdZ8
   ✅ Success
57/260 Downloading: QVRwOOczbkQ
   ❌ Failed
58/260 Downloading: CjBEYyY_zAo
   ❌ Failed
59/260 Downloading: eX5Arj3tCtk
   ✅ Success
60/260 Downloading: b1IDJ3pESyQ
   ✅ Success
61/260 Downloading: 5nwMi6jIBsw
   ❌ Failed
62/260 Downloading: nT1D2vwXmpc
   ✅ Success
63/260 Downloading: 8HASYg_rWtI
   ✅ Success
64/260 Downloading: Ll_q4ROVnpM
   ✅ Success
65/260 Downloading: k2QmGOZTgI4
   ✅ Success
66/260 Downloading: IbNRbt85y2U
   ✅ Success
67/260 Downloading: ShT9kuMlRWg
   ✅ Success
68/260 Downloading: qujAC8ix2iU
   ✅ Success
69/260 Downloading: 9CKXMBiPZM4
   ✅ Success
70/260 Downloading: 0og-bzSSVn8
   ❌ Failed
71/260 Downloading: BzLItAMFXto
   ✅ Success
72/260 Downloading: 52Yoee8fbLI
   ✅ Success
73/260 Downloading: qUuUpSIeo4g
   ✅ Success
74/260 Downloading: 4_ZZFKjjoL0
   ✅ Success
75/260 Downloading: rkw6PdThaxQ
   ✅ Success
76/260 Downloading: o9xCASah21I
   ✅ Success
77/260 Downloading: gpecurYnY2k
   ✅ Success
78/260 Downloading: cX9NRa9P2oU
   ✅ Success
79/260 Downloading: sXVRrpisEbg
   ✅ Success
80/260 Downloading: soDWe_mNYYg
   ✅ Success
81/260 Downloading: An4ZXnZAaoo
   ❌ Failed
82/260 Downloading: 9YKzan280sE
   ✅ Success
83/260 Downloading: eSyA_RsT1nc
   ✅ Success
84/260 Downloading: Tb6yv56nGao
   ❌ Failed
85/260 Downloading: x-rrn1-wZH4
   ✅ Success
86/260 Downloading: 9VAIrq9d-Iw
   ✅ Success
87/260 Downloading: fL-vp4_Ap-k
   ✅ Success
88/260 Downloading: qgLDdlvdBGQ
   ✅ Success
89/260 Downloading: UX8eJYcKS3k
   ✅ Success
90/260 Downloading: L52CaHaHrZc
   ✅ Success
91/260 Downloading: msdg7CXgrHU
   ✅ Success
92/260 Downloading: H_VpJUoVtI4
   ✅ Success
93/260 Downloading: Jv8yXmBjEnc
   ✅ Success
94/260 Downloading: G_l1XUlFF4E
   ✅ Success
95/260 Downloading: Ak0wxUETZS8
   ✅ Success
96/260 Downloading: zU1D3Ze3PZ0
   ✅ Success
97/260 Downloading: TMj00-mVkYc
   ✅ Success
98/260 Downloading: LjHOYz7q1YQ
   ✅ Success
99/260 Downloading: WhJ3Urk2uUA
   ✅ Success
100/260 Downloading: Sm_670Aqo5g
   ✅ Success
101/260 Downloading: a8-_OiB1sJY
   ✅ Success
102/260 Downloading: C2TYCbmHxck
   ✅ Success
103/260 Downloading: 82JA1D4xleE
   ✅ Success
104/260 Downloading: 3M3FsgEyWW8
   ✅ Success
105/260 Downloading: Y6KnuVj8OZQ
   ✅ Success
106/260 Downloading: 6rSD9uaIAQw
   ✅ Success
107/260 Downloading: 8tWvr59ebM8
   ✅ Success
108/260 Downloading: NXD8HAe31bM
   ✅ Success
109/260 Downloading: HXaBF2nmsms
   ✅ Success
110/260 Downloading: 3SilJJGInak
   ❌ Failed
111/260 Downloading: _JjkMCq9pNQ
   ✅ Success
112/260 Downloading: yAXvUPPYnpk
   ✅ Success
113/260 Downloading: -r7Yk-N2Z4U
   ✅ Success
114/260 Downloading: j3_k93jEWtU
   ✅ Success
115/260 Downloading: T56RZeirWQo
   ✅ Success
116/260 Downloading: tkiXsMogwZE
   ✅ Success
117/260 Downloading: cBYAkkaX8G4
   ✅ Success
118/260 Downloading: NdLuP-KlScQ
   ✅ Success
119/260 Downloading: gtx3zFfXh-s
   ❌ Failed
120/260 Downloading: h6b8EQ9Rso0
   ❌ Failed
121/260 Downloading: m1lAISBFvxE
   ✅ Success
122/260 Downloading: 9JLNq3hDOY0
   ✅ Success
123/260 Downloading: 1RcjvfLX8Ms
   ❌ Failed
124/260 Downloading: AoAfewp_kaY
   ✅ Success
125/260 Downloading: 2WMjVrY444M
   ✅ Success
126/260 Downloading: t5RfGyNwR5w
   ❌ Failed
127/260 Downloading: zC3dmdnv1KY
   ✅ Success
128/260 Downloading: 3CuNbYB5scs
   ✅ Success
129/260 Downloading: EGVceuMZU3o
   ✅ Success
130/260 Downloading: gqRqHm6gAS0
   ✅ Success
131/260 Downloading: ngHmt25_--M
   ✅ Success
132/260 Downloading: iQ5lVnRRooE
   ✅ Success
133/260 Downloading: 89Ln2tDYVyU
   ✅ Success
134/260 Downloading: f_7eK3sqN7M
   ✅ Success
135/260 Downloading: i4odiaaqrfQ
   ✅ Success
136/260 Downloading: sbgGB3DRo5g
   ✅ Success
137/260 Downloading: UWxYo-rB1vI
   ✅ Success
138/260 Downloading: IPKni-3INXQ
   ✅ Success
139/260 Downloading: cP0KDo0H944
   ✅ Success
140/260 Downloading: KNcYRuDt02M
   ✅ Success
141/260 Downloading: 9m6i3tZaqS0
   ✅ Success
142/260 Downloading: TJ_7iTquH-I
   ✅ Success
143/260 Downloading: 6ouVOgddKoc
   ✅ Success
144/260 Downloading: D8nus_iz9sA
   ✅ Success
145/260 Downloading: qM4htNJL-iw
   ✅ Success
146/260 Downloading: dPcmsMfoeTU
   ✅ Success
147/260 Downloading: gy6PrIiLh6I
   ✅ Success
148/260 Downloading: 4Vltzmw0O3Y
   ✅ Success
149/260 Downloading: pcmatMy0-XY
   ✅ Success
150/260 Downloading: imO76QQACec
   ✅ Success
151/260 Downloading: YB7_horpUGQ
   ✅ Success
152/260 Downloading: kCyej2X1Sf8
   ✅ Success
153/260 Downloading: iYxMhVSOC9Y
   ✅ Success
154/260 Downloading: 4vCBb5s41Ms
   ✅ Success
155/260 Downloading: FL7EAu5HZM8
   ✅ Success
156/260 Downloading: megW4yRhdYA
   ❌ Failed
157/260 Downloading: yxZ28BjFeM0
   ✅ Success
158/260 Downloading: 7JseGlbiLx8
   ❌ Failed
159/260 Downloading: ryBtQ672mDY
   ✅ Success
160/260 Downloading: Rfy8aecdhO8
   ✅ Success
161/260 Downloading: 7VrxYYOWQ6o
   ❌ Failed
162/260 Downloading: CupakwHJSFw
   ✅ Success
163/260 Downloading: nAxyUNUuI_Y
   ✅ Success
164/260 Downloading: RkL41-4yG1Q
   ✅ Success
165/260 Downloading: AfsghWF11bg
   ❌ Failed
166/260 Downloading: TGwxnxvq8d0
   ✅ Success
167/260 Downloading: WDk_ccFHrZw
   ✅ Success
168/260 Downloading: yLd5HqLiFQw
   ✅ Success
169/260 Downloading: SeJ-8_KxfRg
   ❌ Failed
170/260 Downloading: 13J_WcKx3Qo
   ✅ Success
171/260 Downloading: HMlVK92Vrgw
   ✅ Success
172/260 Downloading: rZUq56OMlPA
   ❌ Failed
173/260 Downloading: 9gCfNKhR3-g
   ✅ Success
174/260 Downloading: B066YDLDvh0
   ✅ Success
175/260 Downloading: xDqpS908aCA
   ✅ Success
176/260 Downloading: srNmFdjxikw
   ✅ Success
177/260 Downloading: SK-rH-2i7-Q
   ✅ Success
178/260 Downloading: TpIy4vjeQZ0
   ✅ Success
179/260 Downloading: J4GgFgjpbuQ
   ✅ Success
180/260 Downloading: jpPEG7GadK8
   ✅ Success
181/260 Downloading: zbg5qfJv3_E
   ❌ Failed
182/260 Downloading: 6rXgD5JlYxY
   ✅ Success
183/260 Downloading: 6yUlo4JLfjM
   ✅ Success
184/260 Downloading: s9kARv7Q3Iw
   ✅ Success
185/260 Downloading: IPFeBuT9EPU
   ❌ Failed
186/260 Downloading: 8BMP10rXheA
   ✅ Success
187/260 Downloading: hL2ojQqB5s0
   ✅ Success
188/260 Downloading: HN44iil7vig
   ❌ Failed
189/260 Downloading: LQdBczSrxh4
   ✅ Success
190/260 Downloading: EgMHjS0bETc
   ✅ Success
191/260 Downloading: 7MOvW1MpbTs
   ❌ Failed
192/260 Downloading: bc7-Uv_5BEA
   ✅ Success
193/260 Downloading: OznJrXrSegE
   ✅ Success
194/260 Downloading: EZ6WrRosvlo
   ❌ Failed
195/260 Downloading: yTk51Fd59Zo
   ✅ Success
196/260 Downloading: Bvrj8fbttTo
   ✅ Success
197/260 Downloading: kUXyYT0l9QY
   ✅ Success
198/260 Downloading: DZ1ZtVAXbTg
   ✅ Success
199/260 Downloading: VgnX5QCMBTQ
   ❌ Failed
200/260 Downloading: 82eOAbQe3tk
   ✅ Success
201/260 Downloading: xKz9z_eEq3s
   ❌ Failed
202/260 Downloading: sT6ZISqsSfA
   ❌ Failed
203/260 Downloading: LjgjqdENqHs
   ❌ Failed
204/260 Downloading: boFaPXi80RI
   ✅ Success
205/260 Downloading: HhAYsIJB7Ug
   ✅ Success
206/260 Downloading: BVhISZcrrI0
   ❌ Failed
207/260 Downloading: QpqHkEBZ0Ao
   ✅ Success
208/260 Downloading: 4mQIYQmVYWQ
   ✅ Success
209/260 Downloading: mNtqZo6DNKI
   ✅ Success
210/260 Downloading: W9gJ7g0bbvs
   ✅ Success
211/260 Downloading: XQxdQBggiPA
   ✅ Success
212/260 Downloading: QVyYjJLKNl8
   ✅ Success
213/260 Downloading: Uxe-6s7__wA
   ✅ Success
214/260 Downloading: GACIkkMwTWw
   ✅ Success
215/260 Downloading: OhpPejVhlAI
   ✅ Success
216/260 Downloading: GDGq_8bFVxQ
   ✅ Success
217/260 Downloading: dF3R9d-NA_A
   ✅ Success
218/260 Downloading: BZmsjEHQf4k
   ✅ Success
219/260 Downloading: yyy2GCpeGgA
   ✅ Success
220/260 Downloading: fdIj-BzqnmU
   ✅ Success
221/260 Downloading: qg4n3pA9VXc
   ✅ Success
222/260 Downloading: Y-5_affLgXU
   ✅ Success
223/260 Downloading: NVuxT7-9fb8
   ✅ Success
224/260 Downloading: 7CE4DVXEnXQ
   ❌ Failed
225/260 Downloading: aqA9tTQNKuQ
   ✅ Success
226/260 Downloading: Jrm2HZB12_4
   ✅ Success
227/260 Downloading: wJH-9PLOcA0
   ❌ Failed
228/260 Downloading: yx-6tARu5mc
   ✅ Success
229/260 Downloading: egQQnBz5kyo
   ❌ Failed
230/260 Downloading: -B68bRDzQi8
   ✅ Success
231/260 Downloading: IRguTZG7Z6Y
   ✅ Success
232/260 Downloading: zcKrANpkVFU
   ✅ Success
233/260 Downloading: Z55hpcXVE4M
   ✅ Success
234/260 Downloading: EzVLl-tadGA
   ✅ Success
235/260 Downloading: KrUIbD-LqIY
   ✅ Success
236/260 Downloading: faidugZ8Lh0
   ✅ Success
237/260 Downloading: SsG2EriUrDo
   ✅ Success
238/260 Downloading: sS4NEhWjRss
   ✅ Success
239/260 Downloading: ERvQPTTWugE
   ✅ Success
240/260 Downloading: 5keujP8jp98
   ✅ Success
241/260 Downloading: FaxWqQazOlk
   ✅ Success
242/260 Downloading: p6dxe62YYbQ
   ❌ Failed
243/260 Downloading: iD9RhUTIqVE
   ✅ Success
244/260 Downloading: dIwvrN5x_mU
   ✅ Success
245/260 Downloading: a9KJpVbt1T0
   ✅ Success
246/260 Downloading: V90vfoGo6hg
   ✅ Success
247/260 Downloading: -_u5wrx8Ffo
   ✅ Success
248/260 Downloading: NWrGrp7ynj0
   ✅ Success
249/260 Downloading: VeCSHwtkBZU
   ✅ Success
250/260 Downloading: 2xWH7McfIVA
   ✅ Success
251/260 Downloading: 2guF3-4V-NY
   ❌ Failed
252/260 Downloading: t39KsRsRHYk
   ✅ Success
253/260 Downloading: ac_NV-KVbyo
   ✅ Success
254/260 Downloading: nayZ_NorgcM
   ✅ Success
255/260 Downloading: pIpTRHXyLb4
   ✅ Success
256/260 Downloading: lJLxyqixPQI
   ✅ Success
257/260 Downloading: _f6h4szQ994
   ✅ Success
258/260 Downloading: FhVgZ4jc0sc
   ✅ Success
259/260 Downloading: DqAedcp5q6s
   ✅ Success
260/260 Downloading: W5iexBflhRs
   ✅ Success

==============================
SIREN DOWNLOAD COMPLETE
==============================
Successful: 222
Already existed: 0
Failed: 38
Results saved to: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata/siren_download_results.csv