In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

BASE_DIR = "/content/drive/MyDrive/SafeCue Audio Recordings"

print("Folder exists:", os.path.exists(BASE_DIR))
print("\nContents:")

for item in os.listdir(BASE_DIR):
    print("📁", item)

Folder exists: True

Contents:
📁 Siren
📁 Fire Alarm
📁 Smoke Alarm
📁 Screaming
📁 Background Noise
📁 _metadata

In [ ]:
!pip install -q yt-dlp
!apt-get -qq update
!apt-get -qq install ffmpeg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.7/183.7 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 69.6 MB/s eta 0:00:00
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)

In [ ]:
import os

METADATA_DIR = os.path.join(BASE_DIR, "_metadata")
os.makedirs(METADATA_DIR, exist_ok=True)

print("Metadata folder:", METADATA_DIR)

Metadata folder: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata

In [ ]:
import pandas as pd

metadata_url = "https://research.google.com/audioset/download.html"

print("AudioSet metadata page:")
print(metadata_url)

AudioSet metadata page:
https://research.google.com/audioset/download.html

In [ ]:
!wget -q --show-progress \
"https://huggingface.co/datasets/agkphysics/AudioSet/resolve/main/balanced_train_segments.csv" \
-o /dev/null

In [ ]:
import os

print(os.listdir(METADATA_DIR))

['unbalanced_train_segments.csv', 'siren_download_results.csv', 'fire_alarm_download_results.csv', 'smoke_alarm_download_results.csv', 'screaming_download_results.csv', 'balanced_train_segments.csv', 'ontology.json']

In [ ]:

import requests

url = "https://research.google.com/audioset/download.html"
response = requests.get(url)

print("Status code:", response.status_code)
print("Page downloaded:", len(response.text) > 0)

Status code: 200
Page downloaded: True

In [ ]:
import requests

url = "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/balanced_train_segments.csv"

output_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

response = requests.get(url)

with open(output_path, "wb") as f:
    f.write(response.content)

print("Downloaded:", output_path)
print("File size:", os.path.getsize(output_path), "bytes")

Downloaded: /content/drive/MyDrive/SafeCue Audio Recordings/_metadata/balanced_train_segments.csv
File size: 1211931 bytes

In [ ]:

csv_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

with open(csv_path, "r", encoding="utf-8") as f:
    for i in range(8):
        print(f"LINE {i+1}:", repr(f.readline()))

LINE 1: '# Segments csv created Sun Mar  5 10:54:31 2017\n'
LINE 2: '# num_ytids=22160, num_segs=22160, num_unique_labels=527, num_positive_labels=52882\n'
LINE 3: '# YTID, start_seconds, end_seconds, positive_labels\n'
LINE 4: '--PJHxphWEs, 30.000, 40.000, "/m/09x0r,/t/dd00088"\n'
LINE 5: '--ZhevVpy1s, 50.000, 60.000, "/m/012xff"\n'
LINE 6: '--aE2O5G5WE, 0.000, 10.000, "/m/03fwl,/m/04rlf,/m/09x0r"\n'
LINE 7: '--aO5cdqSAg, 30.000, 40.000, "/t/dd00003,/t/dd00005"\n'
LINE 8: '--aaILOrkII, 200.000, 210.000, "/m/032s66,/m/073cg4"\n'

In [ ]:
import csv
import pandas as pd
import os

csv_path = os.path.join(METADATA_DIR, "balanced_train_segments.csv")

rows = []

with open(csv_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if row and not row[0].startswith("#"):
            rows.append(row)

df = pd.DataFrame(
    rows,
    columns=["YTID", "start_seconds", "end_seconds", "positive_labels"]
)

print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

Shape: (22160, 4)

First 5 rows:

          YTID start_seconds end_seconds             positive_labels
0  --PJHxphWEs        30.000      40.000         /m/09x0r,/t/dd00088
1  --ZhevVpy1s        50.000      60.000                   /m/012xff
2  --aE2O5G5WE         0.000      10.000  /m/03fwl,/m/04rlf,/m/09x0r
3  --aO5cdqSAg        30.000      40.000       /t/dd00003,/t/dd00005
4  --aaILOrkII       200.000     210.000         /m/032s66,/m/073cg4

In [ ]:
import requests
import json
import os

ontology_url = "https://raw.githubusercontent.com/audioset/ontology/master/ontology.json"
ontology_path = os.path.join(METADATA_DIR, "ontology.json")

response = requests.get(ontology_url)
response.raise_for_status()

with open(ontology_path, "wb") as f:
    f.write(response.content)

print("Ontology downloaded successfully!")
print("File size:", os.path.getsize(ontology_path), "bytes")

Ontology downloaded successfully!
File size: 342780 bytes

In [ ]:
import json

with open(ontology_path, "r", encoding="utf-8") as f:
    ontology = json.load(f)

keyword = "Outside, urban or manmade"

print(f"\n=== {keyword.upper()} ===")

matches = []

for item in ontology:
    name = item.get("name", "")

    if keyword.lower() in name.lower():
        matches.append((item.get("id"), name))

for audio_id, name in matches:
    print(audio_id, "→", name)

=== OUTSIDE, URBAN OR MANMADE ===
/t/dd00128 → Outside, urban or manmade

In [ ]:
background_noise = "/t/dd00128"
count = df["positive_labels"].apply(lambda x: background_noise in x.split(",")
    ).sum()
print(f"Background Noise: {count} clips")

Background Noise: 256 clips

In [ ]:
import requests
import os

url = "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/unbalanced_train_segments.csv"

output_path = os.path.join(METADATA_DIR, "unbalanced_train_segments.csv")

response = requests.get(url)
response.raise_for_status()

with open(output_path, "wb") as f:
    f.write(response.content)

print("Downloaded successfully!")
print("File size:", os.path.getsize(output_path), "bytes")

Downloaded successfully!
File size: 101468408 bytes

In [ ]:
import csv
from collections import Counter

unbalanced_path = os.path.join(
    METADATA_DIR,
    "unbalanced_train_segments.csv"
)

background_noise_id = "/t/dd00128"

counts = 0

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        if background_noise_id in labels:
          counts += 1

print("AudioSet unbalanced training counts:")
print("Background Noise in balanced dataset:", counts, "clips")

AudioSet unbalanced training counts:
Background Noise in balanced dataset: 33861 clips

In [ ]:
background_noise_id =  "/t/dd00128"
background_noise_rows = df[df["positive_labels"].apply(lambda x: background_noise_id in x.split(","))].reset_index(drop = True)
print("Background Noise Clips Available: ", len(background_noise_rows))
print("\nFirst Background Noise Clip: ")
display(background_noise_rows.head(1))

Background Noise Clips Available:  256

First Background Noise Clip:

,YTID,start_seconds,end_seconds,positive_labels
0,-LBl0UeKNyU,430.000,440.000,"/m/07p6mqd,/m/09x0r,/t/dd00125,/t/dd00128"

In [ ]:
import subprocess
import os
import time

# Number of clips to test
NUM_TEST = 10

# Use the first 10 Background Noise clips
test_rows = background_noise_rows.head(NUM_TEST)

background_noise_folder = os.path.join(BASE_DIR, "Background Noise")
os.makedirs(background_noise_folder, exist_ok=True)

success = 0
failed = 0

for i, row in test_rows.iterrows():
    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        background_noise_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # Skip if already downloaded
    if os.path.exists(output_file):
        print(f"Already exists: {ytid}")
        success += 1
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(f"Downloading {success + failed + 1}/{NUM_TEST}: {ytid}")

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        success += 1
        print("  ✅ Success")
    else:
        failed += 1
        print("  ❌ Failed")

    time.sleep(1)

print("\n====================")
print("DOWNLOAD TEST COMPLETE")
print("====================")
print("Successful:", success)
print("Failed:", failed)

Downloading 1/10: -LBl0UeKNyU
  ❌ Failed
Already exists: -RRi3QktLdc
Already exists: -WmL01c-4ZE
Already exists: -mNbbwgUZtQ
Already exists: 0gcJJ_M3gP0
Already exists: 0jaaX-we-8g
Already exists: 19DRe0cdeXQ
Already exists: 1ObaLGDunXY
Already exists: 1d0fsHq1qks
Already exists: 1qAvaKlkJis

====================
DOWNLOAD TEST COMPLETE
====================
Successful: 9
Failed: 1

In [ ]:
background_noise_candidates = background_noise_rows.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print(
    "Total Background Noise candidates:",
    len(background_noise_candidates)
)

print("\nFirst 10 candidates:")
display(background_noise_candidates.head(10))

Total Background Noise candidates: 256

First 10 candidates:

,YTID,start_seconds,end_seconds,positive_labels
0,-LBl0UeKNyU,430.000,440.000,"/m/07p6mqd,/m/09x0r,/t/dd00125,/t/dd00128"
1,-RRi3QktLdc,500.000,510.000,"/m/09x0r,/m/0ytgt,/t/dd00013,/t/dd00128"
2,-WmL01c-4ZE,20.000,30.000,"/m/07rjzl8,/m/09x0r,/t/dd00128"
3,-mNbbwgUZtQ,140.000,150.000,"/m/02mk9,/m/03p19w,/m/09x0r,/t/dd00128"
4,0gcJJ_M3gP0,30.000,40.000,"/m/06h7j,/m/09x0r,/t/dd00128"
5,0jaaX-we-8g,0.000,10.000,"/m/07qfr4h,/m/09x0r,/t/dd00128"
6,19DRe0cdeXQ,20.000,30.000,"/m/028v0c,/m/07r4wb8,/t/dd00128"
7,1ObaLGDunXY,50.000,60.000,"/m/04rlf,/m/09x0r,/t/dd00127,/t/dd00128"
8,1d0fsHq1qks,160.000,170.000,"/m/04rlf,/m/07p6mqd,/m/09x0r,/t/dd00128"
9,1qAvaKlkJis,30.000,40.000,"/m/07qn4z3,/t/dd00128"

In [ ]:
import csv
import pandas as pd
import os

unbalanced_path = os.path.join(
    METADATA_DIR,
    "unbalanced_train_segments.csv"
)

background_noise_id = "/t/dd00128"

background_noise_unbalanced_rows = []

with open(unbalanced_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f, skipinitialspace=True)

    for row in reader:
        if not row or row[0].startswith("#"):
            continue

        labels = row[3].split(",")

        if background_noise_id in labels:
            background_noise_unbalanced_rows.append(row)

background_noise_unbalanced = pd.DataFrame(
    background_noise_unbalanced_rows,
    columns=[
        "YTID",
        "start_seconds",
        "end_seconds",
        "positive_labels"
    ]
)

# Remove duplicate YouTube videos
background_noise_unbalanced = background_noise_unbalanced.drop_duplicates(
    subset=["YTID"]
).reset_index(drop=True)

print(
    "Unique Background Noise candidates in unbalanced set:",
    len(background_noise_unbalanced)
)

display(background_noise_unbalanced.head(10))

Unique Background Noise candidates in unbalanced set: 33861

,YTID,start_seconds,end_seconds,positive_labels
0,--7VmHMn_b4,30.000,40.000,"/m/04rlf,/m/09x0r,/t/dd00128"
1,--K2ZlsdQ4o,30.000,40.000,"/m/07yv9,/t/dd00128"
2,--KYALrhHy4,30.000,40.000,"/m/03qtwd,/m/04rlf,/m/09x0r,/t/dd00128"
3,--KxycEjQtU,60.000,70.000,"/m/09x0r,/t/dd00128"
4,--OqV2-d2E4,280.000,290.000,"/m/07yv9,/m/09x0r,/m/0k4j,/t/dd00128"
5,--PMnfMhn1A,30.000,40.000,"/m/03qtwd,/t/dd00128"
6,--_VuZzBX74,190.000,200.000,"/m/02lkt,/m/04rlf,/t/dd00128"
7,--du6cuRWZs,170.000,180.000,"/m/04rlf,/t/dd00128"
8,--gKfbzT1VY,20.000,30.000,"/m/012ndj,/m/03j1ly,/m/07r04,/m/07yv9,/t/dd00128"
9,--k9htntelY,30.000,40.000,"/m/04rlf,/m/09x0r,/t/dd00128"

In [ ]:
BACKGROUND_NOISE_TARGET = 300

background_noise_download_candidates = background_noise_unbalanced.sample(
    n=BACKGROUND_NOISE_TARGET,
    random_state=42
).reset_index(drop=True)

print("Background Noise Candidates selected:", len(background_noise_download_candidates))

display(background_noise_download_candidates.head(10))

Background Noise Candidates selected: 400

,YTID,start_seconds,end_seconds,positive_labels
0,hxoO4q8EZ0Q,60.000,70.000,"/m/09x0r,/t/dd00128"
1,L2u6Z70YCeg,100.000,110.000,"/m/09x0r,/t/dd00128"
2,u8yRw5XZbFY,140.000,150.000,"/m/012f08,/m/07yv9,/m/0k4j,/t/dd00128"
3,uWNsmuVYJRE,400.000,410.000,"/m/07r04,/m/07yv9,/m/09x0r,/t/dd00128"
4,iWz1YklxRZE,30.000,40.000,"/m/06h7j,/m/09x0r,/t/dd00128"
5,OhGg9w1n5MU,10.000,20.000,"/m/03k3r,/m/04rlf,/m/0jbk,/t/dd00128"
6,A2hfPy_apIU,5.000,15.000,"/m/0912c9,/t/dd00128"
7,jp3AId2qH9E,90.000,100.000,"/m/04rlf,/m/09x0r,/t/dd00128"
8,5CmhBfwuSv8,30.000,40.000,/t/dd00128
9,a-zpKuDFBUg,30.000,40.000,"/m/04_sv,/m/07yv9,/t/dd00128"

In [ ]:
import subprocess
import os
import time
import pandas as pd

background_noise_folder = os.path.join(BASE_DIR, "Background Noise")
os.makedirs(background_noise_folder, exist_ok=True)

results = []

for i, row in background_noise_download_candidates.iterrows():

    ytid = row["YTID"]
    start = row["start_seconds"]
    end = row["end_seconds"]

    output_file = os.path.join(
        background_noise_folder,
        f"{ytid}_{start}_{end}.wav"
    )

    # If already downloaded, don't download again
    if os.path.exists(output_file):
        print(
            f"{i+1}/{len(background_noise_download_candidates)} "
            f"✅ Already exists: {ytid}"
        )

        results.append({
            "YTID": ytid,
            "start_seconds": start,
            "end_seconds": end,
            "label": "Background Noise",
            "filename": output_file,
            "status": "already_exists"
        })
        continue

    url = f"https://www.youtube.com/watch?v={ytid}"

    command = [
        "yt-dlp",
        "--no-playlist",
        "--quiet",
        "--no-warnings",
        "--extract-audio",
        "--audio-format", "wav",
        "--download-sections", f"*{start}-{end}",
        "-o", output_file,
        url
    ]

    print(
        f"{i+1}/{len(background_noise_download_candidates)} "
        f"Downloading: {ytid}"
    )

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode == 0 and os.path.exists(output_file):
        status = "success"
        print("   ✅ Success")
    else:
        status = "failed"
        print("   ❌ Failed")
        print("   ERROR:", result.stderr)
    results.append({
        "YTID": ytid,
        "start_seconds": start,
        "end_seconds": end,
        "label": "Background Noise",
        "filename": output_file if status == "success" else "",
        "status": status
    })

    time.sleep(1)

# Save download results
download_results = pd.DataFrame(results)

results_path = os.path.join(
    METADATA_DIR,
    "background_noise_download_results.csv"
)

download_results.to_csv(results_path, index=False)

print("\n====================================")
print("BACKGROUND NOISE DOWNLOAD COMPLETE")
print("====================================")
print(
    "Successful:",
    (download_results["status"] == "success").sum()
)
print(
    "Already existed:",
    (download_results["status"] == "already_exists").sum()
)
print(
    "Failed:",
    (download_results["status"] == "failed").sum()
)
print("Results saved to:", results_path)

1/400 ✅ Already exists: hxoO4q8EZ0Q
2/400 ✅ Already exists: L2u6Z70YCeg
3/400 ✅ Already exists: u8yRw5XZbFY
4/400 ✅ Already exists: uWNsmuVYJRE
5/400 ✅ Already exists: iWz1YklxRZE
6/400 ✅ Already exists: OhGg9w1n5MU
7/400 ✅ Already exists: A2hfPy_apIU
8/400 ✅ Already exists: jp3AId2qH9E
9/400 ✅ Already exists: 5CmhBfwuSv8
10/400 ✅ Already exists: a-zpKuDFBUg
11/400 ✅ Already exists: rD2sMlMM2TU
12/400 ✅ Already exists: xU5_flIx-dA
13/400 ✅ Already exists: nCGKsjIJbiE
14/400 Downloading: YhJ1NaLBj9U
   ❌ Failed
   ERROR: ERROR: [youtube] YhJ1NaLBj9U: Video unavailable

15/400 ✅ Already exists: 0jS8QrZDNtY
16/400 ✅ Already exists: dClkN6MtQcE
17/400 ✅ Already exists: II7LEtbM4IU
18/400 ✅ Already exists: 5fyzKTSL20w
19/400 ✅ Already exists: EyI1dCPaJPg
20/400 ✅ Already exists: Hz9XowPzXxI
21/400 Downloading: cSrv7Ed-Au4
   ❌ Failed
   ERROR: ERROR: [youtube] cSrv7Ed-Au4: This video is not available

22/400 ✅ Already exists: 710INRXyTus
23/400 ✅ Already exists: l5XFK0ChW6A
24/400 ✅ Already exists: K43yCQwwCxQ
25/400 Downloading: ojoH2wL2stY
   ❌ Failed
   ERROR: ERROR: [youtube] ojoH2wL2stY: Sign in to confirm your age. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

26/400 ✅ Already exists: KFSm9DPxMFo
27/400 ✅ Already exists: 9i020CoQAek
28/400 ✅ Already exists: EcoY2vVHGvw
29/400 ✅ Already exists: zGxtX591zdo
30/400 Downloading: T_4Y3ujE3sg
   ❌ Failed
   ERROR: ERROR: [youtube] T_4Y3ujE3sg: This video is unavailable

31/400 ✅ Already exists: Bft2swvjo5U
32/400 ✅ Already exists: UDJR47i-KB4
33/400 ✅ Already exists: AS_AT2Y9zRA
34/400 ✅ Already exists: AEfZlcAWD4M
35/400 ✅ Already exists: vb95udalhBw
36/400 ✅ Already exists: uU4D-jeVpHg
37/400 ✅ Already exists: 8WbUPEYjo1o
38/400 ✅ Already exists: tyItqZBFygo
39/400 Downloading: cQNMNQVbTHc
   ❌ Failed
   ERROR: ERROR: [youtube] cQNMNQVbTHc: Private video

40/400 Downloading: 3jK0_3RCwB4
   ✅ Success
41/400 Downloading: GDY2cLN32sg
   ❌ Failed
   ERROR: ERROR: [youtube] GDY2cLN32sg: This video is unavailable

42/400 Downloading: njSQkDLQqoU
   ❌ Failed
   ERROR: ERROR: [youtube] njSQkDLQqoU: Private video

43/400 Downloading: mDru9x5gD9w
   ✅ Success
44/400 Downloading: pMsnDIZ_dGI
   ✅ Success
45/400 Downloading: UZyuWm8e-I0
   ✅ Success
46/400 Downloading: G-nImCUT2ts
   ✅ Success
47/400 Downloading: c4jeflIf5bY
   ❌ Failed
   ERROR: ERROR: [youtube] c4jeflIf5bY: This video has been removed for violating YouTube's policy on hate speech. Learn more about combating hate speech in your country.

48/400 Downloading: xXPweGNQc2c
   ✅ Success
49/400 Downloading: s_jX6Xpiu2c
   ✅ Success
50/400 Downloading: 5Qw_ttxzn6Q
   ✅ Success
51/400 Downloading: ofNjrTvN_Ws
   ✅ Success
52/400 Downloading: j2Di0pTkvBo
   ✅ Success
53/400 Downloading: 6919FtG5JDg
   ✅ Success
54/400 Downloading: k11Vg0-aGRY
   ✅ Success
55/400 Downloading: 1RMk4KJoztw
   ✅ Success
56/400 Downloading: xpt0o7A0s0Y
   ✅ Success
57/400 Downloading: p2z8q2-Gx34
   ✅ Success
58/400 Downloading: 9NJSicpWIM4
   ❌ Failed
   ERROR:

ERROR: ffmpeg exited with code 8

59/400 Downloading: gBgGMbpbGMo
   ✅ Success
60/400 Downloading: _d4nojWS7lw
   ✅ Success
61/400 Downloading: mib13XCpf6g
   ✅ Success
62/400 Downloading: P97Mxakh1O8
   ✅ Success
63/400 Downloading: PdLG0ACjVl0
   ❌ Failed
   ERROR: ERROR: [youtube] PdLG0ACjVl0: Private video

64/400 Downloading: ePq3j_KwKrA
   ✅ Success
65/400 Downloading: nyYcD9FU_vw
   ✅ Success
66/400 Downloading: VW2MndvltDU
   ✅ Success
67/400 Downloading: nPctaVYYru4
   ✅ Success
68/400 Downloading: 1aKYfCYQwaQ
   ✅ Success
69/400 Downloading: HYzKNeEFzMM
   ❌ Failed
   ERROR: ERROR: [youtube] HYzKNeEFzMM: This video is unavailable

70/400 Downloading: EfVHED19GQg
   ✅ Success
71/400 Downloading: 1M60LzdWMvE
   ✅ Success
72/400 Downloading: fGdMlNU3TJ0
   ✅ Success
73/400 Downloading: 1R8r5MLh9jM
   ✅ Success
74/400 Downloading: a2itwgYUSjI
   ✅ Success
75/400 Downloading: mCIIrlqbxeM
   ✅ Success
76/400 Downloading: LHGBhnR5nX8
   ❌ Failed
   ERROR: ERROR: [youtube] LHGBhnR5nX8: This video is unavailable

77/400 Downloading: RJosM3f1eqY
   ❌ Failed
   ERROR: ERROR: [youtube] RJosM3f1eqY: This video is unavailable

78/400 Downloading: sAHIIXGSZgs
   ✅ Success
79/400 Downloading: t_kz8Fb6HH8
   ✅ Success
80/400 Downloading: GB_HmamOa3s
   ✅ Success
81/400 Downloading: 7zTlRBg_w_A
   ✅ Success
82/400 Downloading: ydyfDIjnPZs
   ✅ Success
83/400 Downloading: EmE7UqJemRI
   ✅ Success
84/400 Downloading: VyO__KiJAYw
   ✅ Success
85/400 Downloading: SorJjJTMD2Q
   ✅ Success
86/400 Downloading: 1NTP9QsABD8
   ✅ Success
87/400 Downloading: t6rNFcleh3Q
   ✅ Success
88/400 Downloading: sB3jXAg6PLg
   ✅ Success
89/400 Downloading: FDanOo7V9Q8
   ✅ Success
90/400 Downloading: pT0jKPWpa8g
   ✅ Success
91/400 Downloading: jYPY4yWKI00
   ✅ Success
92/400 Downloading: Xp8oKFVv6t4
   ❌ Failed
   ERROR: ERROR: [youtube] Xp8oKFVv6t4: Private video

93/400 Downloading: kd4Hm4lSZN8
   ❌ Failed
   ERROR: ERROR: [youtube] kd4Hm4lSZN8: Video unavailable

94/400 Downloading: hDwTJ6P9NVw
   ✅ Success
95/400 Downloading: 71CSn7eTYOg
   ✅ Success
96/400 Downloading: OiwKuZXYi9k
   ✅ Success
97/400 Downloading: BtA8u359QQw
   ✅ Success
98/400 Downloading: jvIiuiXQbe4
   ✅ Success
99/400 Downloading: 12iyyxnjiCs
   ✅ Success
100/400 Downloading: W2YSbPUHvNo
   ✅ Success
101/400 Downloading: Uw6n_lzUMlk
   ❌ Failed
   ERROR: ERROR: [youtube] Uw6n_lzUMlk: This video is unavailable

102/400 Downloading: iWAANnNBmrM
   ✅ Success
103/400 Downloading: UvqUiO6Glco
   ✅ Success
104/400 Downloading: D14ZI2B-q2E
   ✅ Success
105/400 Downloading: K_9HDuBC4mg
   ✅ Success
106/400 Downloading: DQtsLyfNI0k
   ✅ Success
107/400 Downloading: M_6Mu2cyJsk
   ✅ Success
108/400 Downloading: T7bM_V62mr8
   ✅ Success
109/400 Downloading: VirLOj2QLJE
   ✅ Success
110/400 Downloading: D22gsGcLwCw
   ✅ Success
111/400 Downloading: 4HJJJlaxmbk
   ✅ Success
112/400 Downloading: k75UWIurAV4
   ✅ Success
113/400 Downloading: enq9XjshKLw
   ❌ Failed
   ERROR: ERROR: [youtube] enq9XjshKLw: This video is unavailable

114/400 Downloading: u1DZ4MhjuOM
   ✅ Success
115/400 Downloading: 2JIngvgryY8
   ✅ Success
116/400 Downloading: 9cc-7Y0r9J8
   ❌ Failed
   ERROR: ERROR: [youtube] 9cc-7Y0r9J8: Video unavailable

117/400 Downloading: 8TmlPO9WLsA
   ✅ Success
118/400 Downloading: yqsPcm-kVVs
   ✅ Success
119/400 Downloading: CtW8_VszCM4
   ✅ Success
120/400 Downloading: x5YUs6SecDw
   ✅ Success
121/400 Downloading: LSp4f73U40o
   ✅ Success
122/400 Downloading: XnsUTu0whNw
   ✅ Success
123/400 Downloading: Hz_mbGWe39E
   ✅ Success
124/400 Downloading: 9WZZ981az8I
   ❌ Failed
   ERROR:

ERROR: ffmpeg exited with code 8

125/400 Downloading: Iev3Hgt_2GE
   ✅ Success
126/400 Downloading: pcU4ZLvbajk
   ❌ Failed
   ERROR: ERROR: [youtube] pcU4ZLvbajk: This video has been removed for violating YouTube's Community Guidelines

127/400 Downloading: Lf9Peycf6KM
   ✅ Success
128/400 Downloading: 1WamdkYKsB0
   ✅ Success
129/400 Downloading: 9YwYb1YvdRg
   ✅ Success
130/400 Downloading: 0iK4Quxg9mI
   ✅ Success
131/400 Downloading: nlf-9S7_OHo
   ✅ Success
132/400 Downloading: z_HGXie2D58
   ✅ Success
133/400 Downloading: RIJhulQ1LAE
   ❌ Failed
   ERROR: ERROR: [youtube] RIJhulQ1LAE: This video is unavailable

134/400 Downloading: By10MxXkgA0
   ✅ Success
135/400 Downloading: UiOjU1ZeGSI
   ✅ Success
136/400 Downloading: fW1wpnglAJk
   ✅ Success
137/400 Downloading: C2PUN97Rv2k
   ✅ Success
138/400 Downloading: ooIB3SpSsEc
   ✅ Success
139/400 Downloading: cZEXRgZgrKE
   ✅ Success
140/400 Downloading: rRZ9B4qARLk
   ✅ Success
141/400 Downloading: MmMemWn5Qy0
   ✅ Success
142/400 Downloading: RDt_9sK3j08
   ✅ Success
143/400 Downloading: XrpaKmsBuwQ
   ❌ Failed
   ERROR: ERROR: [youtube] XrpaKmsBuwQ: This video is unavailable

144/400 Downloading: LalGdzVzdBs
   ❌ Failed
   ERROR: ERROR: [youtube] LalGdzVzdBs: Private video

145/400 Downloading: tqk4NH9Ls18
   ✅ Success
146/400 Downloading: CuNgdW4DmjI
   ❌ Failed
   ERROR: ERROR: [youtube] CuNgdW4DmjI: This video is unavailable

147/400 Downloading: u0UDFRwViNo
   ✅ Success
148/400 Downloading: c8BTTwsodZ0
   ✅ Success
149/400 Downloading: BJ1ffTFmTco
   ❌ Failed
   ERROR: ERROR: [youtube] BJ1ffTFmTco: Video unavailable

150/400 Downloading: aqFM2BiTYDk
   ✅ Success
151/400 Downloading: z2hSxOOHDJo
   ✅ Success
152/400 Downloading: Vgii7b7tj6M
   ❌ Failed
   ERROR: ERROR: [youtube] Vgii7b7tj6M: Private video

153/400 Downloading: 6khhY7Dk9ss
   ✅ Success
154/400 Downloading: fu6BKJDgWyY
   ✅ Success
155/400 Downloading: Zkds10x5_Cg
   ✅ Success
156/400 Downloading: R_yQhK4n960
   ✅ Success
157/400 Downloading: QCjgc7ctLpU
   ❌ Failed
   ERROR: ERROR: [youtube] QCjgc7ctLpU: This video is unavailable

158/400 Downloading: 4by8ylkvFVM
   ❌ Failed
   ERROR: ERROR: [youtube] 4by8ylkvFVM: Video unavailable

159/400 Downloading: WCx2r_bWXi8
   ✅ Success
160/400 Downloading: NQpr17BBYL8
   ✅ Success
161/400 Downloading: hqlnLlxC1J8
   ✅ Success
162/400 Downloading: VG4P8S6i6GU
   ✅ Success
163/400 Downloading: Gs3eC8E-gbU
   ✅ Success
164/400 Downloading: Ubd3w8N6-2w
   ✅ Success
165/400 Downloading: -sFy6LCLdCg
   ✅ Success
166/400 Downloading: hn8a-vi09wM
   ✅ Success
167/400 Downloading: IY6NbyZB46g
   ✅ Success
168/400 Downloading: 8M4ZJ7tipjA
   ✅ Success
169/400 Downloading: 7LWz2rkn4M0
   ✅ Success
170/400 Downloading: 4X6J3NNEgc8
   ✅ Success
171/400 Downloading: 0HY9u5l1UQo
   ✅ Success
172/400 Downloading: DONo6BBbuqs
   ✅ Success
173/400 Downloading: o2B34Gbfk7s
   ✅ Success
174/400 Downloading: YjcAb5bHOfw
   ✅ Success
175/400 Downloading: tnwhXKYqiXQ
   ✅ Success
176/400 Downloading: YsPT4UqmI9k
   ✅ Success
177/400 Downloading: idE2h5-dVWI
   ✅ Success
178/400 Downloading: ZJO6DFtvBIs
   ✅ Success
179/400 Downloading: JdRJwnI6e8U
   ✅ Success
180/400 Downloading: omgqyucBYv8
   ❌ Failed
   ERROR: ERROR: [youtube] omgqyucBYv8: Private video

181/400 Downloading: Z_tq5ijuiO8
   ✅ Success
182/400 Downloading: SwvY6fkbrNU
   ✅ Success
183/400 Downloading: tl6goqLBhtE
   ✅ Success
184/400 Downloading: x-i8KE683DI
   ✅ Success
185/400 Downloading: kGB3YIYb4Ag
   ✅ Success
186/400 Downloading: U_0dCgAdkEo
   ✅ Success
187/400 Downloading: jVIelJOsun8
   ✅ Success
188/400 Downloading: dUyQHceuI3A
   ✅ Success
189/400 Downloading: u5IMSp0vgsY
   ✅ Success
190/400 Downloading: 6Z63jYaVZU8
   ✅ Success
191/400 Downloading: ZRYHLbeeyJg
   ✅ Success
192/400 Downloading: R5qU9FefimY
   ✅ Success
193/400 Downloading: a3G9s88XdBk
   ✅ Success
194/400 Downloading: Bi1L4vpTPYo
   ✅ Success
195/400 Downloading: Jjmep3yRFsY
   ✅ Success
196/400 Downloading: i1Bsw7F2mc0
   ✅ Success
197/400 Downloading: uvIGXFI8io8
   ✅ Success
198/400 Downloading: AL1D1LIJjqA
   ✅ Success
199/400 Downloading: hmRbMX5Qde0
   ✅ Success
200/400 Downloading: CFwqYlec_Jw
   ❌ Failed
   ERROR: ERROR: [youtube] CFwqYlec_Jw: This video is unavailable

201/400 Downloading: 7YXD50S3tw8
   ✅ Success
202/400 Downloading: YJHDzeJunp4
   ❌ Failed
   ERROR: ERROR: [youtube] YJHDzeJunp4: This video is not available

203/400 Downloading: tNOpzp0-bqw
   ✅ Success
204/400 Downloading: NUAUyeyFdGM
   ✅ Success
205/400 Downloading: tq9ca-I4H80
   ✅ Success
206/400 Downloading: TcQc17XiqE8
   ✅ Success
207/400 Downloading: Lpc2cUV0GYk
   ❌ Failed
   ERROR: ERROR: [youtube] Lpc2cUV0GYk: Private video

208/400 Downloading: bICa8g-8Tg0
   ❌ Failed
   ERROR: ERROR: [youtube] bICa8g-8Tg0: Private video

209/400 Downloading: Nv3BfQ5G2ZU
   ✅ Success
210/400 Downloading: EVIkl79pGQY
   ✅ Success
211/400 Downloading: bAyXtYdETL8
   ✅ Success
212/400 Downloading: ynIN6EsheZU
   ✅ Success
213/400 Downloading: 6wwdfkSS3Ks
   ✅ Success
214/400 Downloading: ZwEfZ0lAEVg
   ✅ Success
215/400 Downloading: RCTjjTnpxj4
   ✅ Success
216/400 Downloading: jBn-6HblbCg
   ✅ Success
217/400 Downloading: ob_R-v6-Dfw
   ✅ Success
218/400 Downloading: kx8_cVuY2oM
   ✅ Success
219/400 Downloading: Szr3PIJ__p0
   ✅ Success
220/400 Downloading: RQxDepmgGnc
   ✅ Success
221/400 Downloading: cev0NrGs2aM
   ✅ Success
222/400 Downloading: n8lcVNBeJc4
   ✅ Success
223/400 Downloading: q4oY4hL9oj0
   ✅ Success
224/400 Downloading: 1hLGqieA8LA
   ✅ Success
225/400 Downloading: CRgBtkFakHo
   ✅ Success
226/400 Downloading: rDs1iVQvZWs
   ✅ Success
227/400 Downloading: jQCuyhvtVQI
   ✅ Success
228/400 Downloading: HEIZxt8PrUk
   ✅ Success
229/400 Downloading: HJ1IO8qJy94
   ❌ Failed
   ERROR: ERROR: [youtube] HJ1IO8qJy94: Video unavailable

230/400 Downloading: 1Kxr1JRGWNE
   ✅ Success
231/400 Downloading: 1dGmguC1hJk
   ✅ Success
232/400 Downloading: Qh_hdBxw8no
   ✅ Success
233/400 Downloading: 3BjdPVVKYiM
   ❌ Failed
   ERROR: ERROR: [youtube] 3BjdPVVKYiM: Video unavailable

234/400 Downloading: 8jplupIma68
   ❌ Failed
   ERROR: ERROR: [youtube] 8jplupIma68: This video is unavailable

235/400 Downloading: 0fybpxOCvi8
   ✅ Success
236/400 Downloading: oTrQjPIwJko
   ❌ Failed
   ERROR: ERROR: [youtube] oTrQjPIwJko: This video is unavailable

237/400 Downloading: UxdxOmTE4fU
   ✅ Success
238/400 Downloading: mhYAvuHPgew
   ✅ Success
239/400 Downloading: WKCODfUXzC0
   ✅ Success
240/400 Downloading: ng5Vm3yQa1w
   ✅ Success
241/400 Downloading: bCDo8W0qD1Y
   ✅ Success
242/400 Downloading: ImNwZZtDZfE
   ✅ Success
243/400 Downloading: Ej6xVZhAm7Y
   ✅ Success
244/400 Downloading: ivbxAF6lT6g
   ✅ Success
245/400 Downloading: EM4j1dcuQnc
   ❌ Failed
   ERROR: ERROR: [youtube] EM4j1dcuQnc: Please sign in. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

246/400 Downloading: rJV2HCru-oA
   ✅ Success
247/400 Downloading: EMwbw4Smfi4
   ✅ Success
248/400 Downloading: rlv45pJ4Zms
   ❌ Failed
   ERROR: ERROR: [youtube] rlv45pJ4Zms: Private video

249/400 Downloading: piFrwFHjY5A
   ✅ Success
250/400 Downloading: ZtFKzXDd8fU
   ✅ Success
251/400 Downloading: wwMHZa2mKL8
   ✅ Success
252/400 Downloading: FOlP3Po3pnk
   ✅ Success
253/400 Downloading: iOFauhZ6S7o
   ✅ Success
254/400 Downloading: 8ygTid0rhvU
   ❌ Failed
   ERROR: ERROR: [youtube] 8ygTid0rhvU: Video unavailable

255/400 Downloading: JbcUuAdz5Wo
   ❌ Failed
   ERROR: ERROR: [youtube] JbcUuAdz5Wo: Video unavailable

256/400 Downloading: 0X2o1vnnuIQ
   ✅ Success
257/400 Downloading: oTRWsKGJmJU
   ✅ Success
258/400 Downloading: qQierb4IX0g
   ❌ Failed
   ERROR: ERROR: [youtube] qQierb4IX0g: Video unavailable

259/400 Downloading: ckwixtXZ86c
   ✅ Success
260/400 Downloading: hEkkz_6lzRs
   ✅ Success
261/400 Downloading: LMOzg1SPqsI
   ❌ Failed
   ERROR: ERROR: [youtube] LMOzg1SPqsI: Private video

262/400 Downloading: Jwb9YJGm4PA
   ✅ Success
263/400 Downloading: txBe_ytp3hI
   ✅ Success
264/400 Downloading: TnHSwBX-FZs
   ✅ Success
265/400 Downloading: GxPoHYm4smQ
   ❌ Failed
   ERROR: ERROR: [youtube] GxPoHYm4smQ: This video has been removed for violating YouTube's Community Guidelines

266/400 Downloading: FTGX7xpi0FA

KeyboardInterrupt: